#!/bin/bash
#
# ./update-changelogs.sh <options>
# Updates ChangeLog files.
#
# e.g. if the main gEDA branch is called origin, then to update all
# ChangeLogs with revisions since the switch to git, do:
#
# ./update-changelogs.sh 1.0-20070526..origin
#
# This should be only be run while preparing a release, in order to
# ensure that the released tarballs contain change logs which can be
# viewed without access to the git repository.
#
#

GCLHEADER="# Do not edit this file - generated from version control history"
GCLFOOTER="#GCL#"

if ! git-status > /dev/null; then
    exit $?
fi

for cl in $(find . -name ChangeLog); do
    echo "Updating ${cl}"
    dir=$(dirname $cl)
    if tail -n1 ${cl} | grep $GCLFOOTER > /dev/null; then
        echo -e "$GCLHEADER\n\n" > $cl
        git-log --pretty=medium $@ -- $dir >> $cl
        echo -e "\n\n$GCLFOOTER" >> $cl
    else
        echo "${cl}: Doesn't appear to be git format log, skipping"
    fi
done
