#!/bin/sh

#CFLAGS="`guile-config compile` `gtk-config --cflags` `libgeda-config --cflags`" 
CFLAGS="`guile-config compile` `pkg-config --cflags gtk+-2.0` `libgeda-config --cflags`" 

MISC_FLAGS="-I/usr/X11R6/include -I../include -I. -I.."

ALES_HACK=-D__GNUC__

make src
cproto $ALES_HACK $CFLAGS $MISC_FLAGS *.c > new_proto

mv -f new_proto ../include/prototype.h
