
_("File")
_("New Window")
_("New Page")
_("Open Page...")
_("Close Page")
_("Revert Page")
_("Save Page")
_("Save Page As...")
_("Save All")
_("Print...")
_("Write image...")
_("Recent files")
_("Execute Script...")
_("Close Window")
_("Quit")

_("Edit")
_("Undo")
_("Redo")
_("Select Mode")
_("Cut Buffer")
_("Copy Buffer")
_("Paste Buffer")
_("Edit...")
_("Edit Text...")
_("Copy Mode")
_("Multiple Copy Mode")
_("Move Mode")
_("Delete")
_("Rotate 90 Mode")
_("Mirror Mode")
_("Slot...")
_("Color...")
_("Lock")
_("Unlock")
_("Line Width & Type...")
_("Fill Type...")
_("Symbol Translate...")
_("Embed Component/Picture")
_("Unembed Component/Picture")
_("Update Component")
_("Show/Hide Inv Text")
_("Make Inv Text Vis")

_("Buffer")
_("Copy into 1")
_("Copy into 2")
_("Copy into 3")
_("Copy into 4")
_("Copy into 5")
_("Cut into 1")
_("Cut into 2")
_("Cut into 3")
_("Cut into 4")
_("Cut into 5")
_("Paste from 1")
_("Paste from 2")
_("Paste from 3")
_("Paste from 4")
_("Paste from 5")

_("View")
_("Redraw")
_("Pan")
_("Zoom Box")
_("Zoom Extents")
_("Zoom In")
_("Zoom Out")
_("Zoom Full")

_("Page")
_("Manager...")
_("Next")
_("Previous")
_("New")
_("Revert")
_("Close")
_("Discard")

_("Add")
_("Component...")
_("Net")
_("Bus")
_("Attribute...")
_("Text...")
_("Line")
_("Box")
_("Circle")
_("Arc")
_("Pin")
_("Picture...")

_("Hierarchy")
_("Down Schematic")
_("Down Symbol")
_("Up")
_("Documentation")

_("Attributes")
_("Attach")
_("Detach")
_("Show Value")
_("Show Name")
_("Show Both")
_("Toggle Visibility")
_("Find Specific Text...")
_("Hide Specific Text...")
_("Show Specific Text...")
_("Autonumber Text...")

_("Options")
_("Text Size...")
_("Cycle grid styles")
_("Toggle Snap On/Off")
_("Snap Grid Spacing...")
_("Scale up Grid Spacing")
_("Scale down Grid Spacing")
_("Toggle Outline/Box")
_("Toggle Net Rubberband")
_("Show Log Window...")
_("Show Coord Window...")

_("Help")
_("Manual")
_("gEDA Documentation")
_("gschem FAQ")
_("Component Documentation")
_("About gschem")
_("Hotkeys")

