
_("_File")
_("New Window")
_("_New")
_("_Open...")
_("Open Recen_t")
_("_Save")
_("Save _As...")
_("Save All")
_("_Revert")
_("_Print...")
_("Write _image...")
_("Execute Script...")
_("_Close")
_("_Quit")

_("_Edit")
_("_Undo")
_("_Redo")
_("Cu_t")
_("_Copy")
_("_Paste")
_("_Delete")
_("Select Mode")
_("Edit...")
_("Edit Text...")
_("Copy Mode")
_("Multiple Copy Mode")
_("Move Mode")
_("Rotate 90 Mode")
_("Mirror Mode")
_("Slot...")
_("Color...")
_("Lock")
_("Unlock")
_("Invoke Macro")
_("Line Width & Type...")
_("Fill Type...")
_("Symbol Translate...")
_("Embed Component/Picture")
_("Unembed Component/Picture")
_("Update Component")
_("Show/Hide Inv Text")
_("Make Inv Text Vis")

_("_Buffer")
_("Copy into 1")
_("Copy into 2")
_("Copy into 3")
_("Copy into 4")
_("Copy into 5")
_("Cut into 1")
_("Cut into 2")
_("Cut into 3")
_("Cut into 4")
_("Cut into 5")
_("Paste from 1")
_("Paste from 2")
_("Paste from 3")
_("Paste from 4")
_("Paste from 5")

_("_View")
_("_Redraw")
_("_Pan")
_("Zoom _Box")
_("Zoom _Extents")
_("Zoom _In")
_("Zoom _Out")
_("Zoom _Full")
_("_Dark color scheme")
_("_Light color scheme")
_("B_W color scheme")

_("_Page")
_("_Manager...")
_("_Previous")
_("_Next")
_("Ne_w")
_("_Revert")
_("_Close")
_("_Discard")

_("_Add")
_("_Component...")
_("_Net")
_("B_us")
_("_Attribute...")
_("_Text...")
_("_Line")
_("_Box")
_("C_ircle")
_("A_rc")
_("_Pin")
_("Pictu_re...")

_("Hie_rarchy")
_("_Down Schematic")
_("Down _Symbol")
_("_Up")
_("D_ocumentation...")

_("A_ttributes")
_("_Attach")
_("_Detach")
_("Show _Value")
_("Show _Name")
_("Show _Both")
_("_Toggle Visibility")
_("_Find Specific Text...")
_("_Hide Specific Text...")
_("_Show Specific Text...")
_("A_utonumber Text...")

_("_Options")
_("_Text Size...")
_("Cycle _grid styles")
_("Toggle _Snap On/Off")
_("Snap Grid S_pacing...")
_("Scale _up Grid Spacing")
_("Scale _down Grid Spacing")
_("Toggle _Outline/Box")
_("Toggle Net _Rubberband")
_("Toggle _Magnetic Net")
_("Show _Log Window...")
_("Show _Coord Window...")

_("_Help")
_("gEDA Docu_mentation...")
_("gschem _FAQ...")
_("gEDA _Wiki...")
_("Component D_ocumentation...")
_("_Hotkeys...")
_("_About...")

