/* structural Verilog generated by gnetlist */
/* WARNING: This is a generated file, edits */
/*        made here will be lost next time  */
/*        you run gnetlist!                 */
/* Id ..........$Id$ */
/* Source.......$Source$ */
/* Revision.....$Revision$ */
/* Author.......$Author$ */

module RIPPLE_COUNT (
       reset ,
       clock ,
       q3 ,
       q2 ,
       q1 ,
       q0
      );

/* Port directions begin here */
input reset ;
input clock ;
output q3 ;
output q2 ;
output q1 ;
output q0 ;


/* Wires from the design */
wire reset ;
wire q3 ;
wire q2 ;
wire q1 ;
wire q0 ;
wire clock ;

/* continuous assignments */

/* Package instantiations */
T_FF U1 ( 
    .clock_ ( clock ),
    .reset_ ( reset ),
    .q_ ( q0 )
    );

T_FF U2 ( 
    .clock_ ( q0 ),
    .reset_ ( reset ),
    .q_ ( q1 )
    );

T_FF U3 ( 
    .clock_ ( q1 ),
    .reset_ ( reset ),
    .q_ ( q2 )
    );

T_FF U4 ( 
    .clock_ ( q2 ),
    .reset_ ( reset ),
    .q_ ( q3 )
    );

endmodule
