/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_MainWindow (void)
{
  GtkWidget *MainWindow;
  GtkWidget *VBoxMain;
  GtkWidget *MenuBar;
  GtkWidget *MenuProject;
  GtkWidget *MenuProject_menu;
  GtkAccelGroup *MenuProject_menu_accels;
  GtkWidget *MenuProjectNew;
  GtkWidget *MenuProjectOpen;
  GtkWidget *MenuProjectProperties;
  GtkWidget *MenuProjectClose;
  GtkWidget *MenuProjectSeparator1;
  GtkWidget *MenuProjectExit;
  GtkWidget *MenuFile;
  GtkWidget *MenuFile_menu;
  GtkAccelGroup *MenuFile_menu_accels;
  GtkWidget *MenuFileEdit;
  GtkWidget *MenuFileSave;
  GtkWidget *MenuFilePrint;
  GtkWidget *MenuFileClose;
  GtkWidget *MenuFileSeparator1;
  GtkWidget *MenuFileNew;
  GtkWidget *MenuFileImport;
  GtkWidget *MenuFileUnlink;
  GtkWidget *MenuFileDelete;
  GtkWidget *MenuAction;
  GtkWidget *MenuTool;
  GtkWidget *MenuWindow;
  GtkWidget *ToolBoxMain;
  GtkWidget *hboxToolBoxMainContainer;
  GtkWidget *ToolBoxUser;
  GtkWidget *ToolBoxClientContainer;
  GtkWidget *VBoxWorkArea;
  GtkWidget *vpaned1;
  GtkWidget *HBoxWorkTopArea;
  GtkWidget *HPaned;
  GtkWidget *ProjectArea;
  GtkWidget *DocNotebook;
  GtkWidget *DocModulesWindow;
  GtkWidget *DocModulesTree;
  GtkWidget *DocModulesLabel;
  GtkWidget *DocFilesWindow;
  GtkWidget *DocFilesTree;
  GtkWidget *DocFilesLabel;
  GtkWidget *StatusArea;
  GtkWidget *scrolledwindow2;
  GtkWidget *StatusText;
  GtkWidget *StatusLabel;
  GtkWidget *StatusBar;

  MainWindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (MainWindow), "MainWindow", MainWindow);
  gtk_window_set_title (GTK_WINDOW (MainWindow), _("gEDA"));
  gtk_window_set_position (GTK_WINDOW (MainWindow), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (MainWindow), 510, 300);

  VBoxMain = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (VBoxMain);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "VBoxMain", VBoxMain,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (VBoxMain);
  gtk_container_add (GTK_CONTAINER (MainWindow), VBoxMain);

  MenuBar = gtk_menu_bar_new ();
  gtk_widget_ref (MenuBar);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuBar", MenuBar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuBar);
  gtk_box_pack_start (GTK_BOX (VBoxMain), MenuBar, FALSE, FALSE, 0);

  MenuProject = gtk_menu_item_new_with_label (_("Project"));
  gtk_widget_ref (MenuProject);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuProject", MenuProject,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuProject);
  gtk_container_add (GTK_CONTAINER (MenuBar), MenuProject);

  MenuProject_menu = gtk_menu_new ();
  gtk_widget_ref (MenuProject_menu);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuProject_menu", MenuProject_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (MenuProject), MenuProject_menu);
  MenuProject_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (MenuProject_menu));

  MenuProjectNew = gtk_menu_item_new_with_label (_("New"));
  gtk_widget_ref (MenuProjectNew);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuProjectNew", MenuProjectNew,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuProjectNew);
  gtk_container_add (GTK_CONTAINER (MenuProject_menu), MenuProjectNew);

  MenuProjectOpen = gtk_menu_item_new_with_label (_("Open"));
  gtk_widget_ref (MenuProjectOpen);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuProjectOpen", MenuProjectOpen,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuProjectOpen);
  gtk_container_add (GTK_CONTAINER (MenuProject_menu), MenuProjectOpen);

  MenuProjectProperties = gtk_menu_item_new_with_label (_("Properties"));
  gtk_widget_ref (MenuProjectProperties);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuProjectProperties", MenuProjectProperties,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuProjectProperties);
  gtk_container_add (GTK_CONTAINER (MenuProject_menu), MenuProjectProperties);

  MenuProjectClose = gtk_menu_item_new_with_label (_("Close"));
  gtk_widget_ref (MenuProjectClose);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuProjectClose", MenuProjectClose,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuProjectClose);
  gtk_container_add (GTK_CONTAINER (MenuProject_menu), MenuProjectClose);

  MenuProjectSeparator1 = gtk_menu_item_new ();
  gtk_widget_ref (MenuProjectSeparator1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuProjectSeparator1", MenuProjectSeparator1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuProjectSeparator1);
  gtk_container_add (GTK_CONTAINER (MenuProject_menu), MenuProjectSeparator1);
  gtk_widget_set_sensitive (MenuProjectSeparator1, FALSE);

  MenuProjectExit = gtk_menu_item_new_with_label (_("Exit"));
  gtk_widget_ref (MenuProjectExit);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuProjectExit", MenuProjectExit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuProjectExit);
  gtk_container_add (GTK_CONTAINER (MenuProject_menu), MenuProjectExit);

  MenuFile = gtk_menu_item_new_with_label (_("File"));
  gtk_widget_ref (MenuFile);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuFile", MenuFile,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuFile);
  gtk_container_add (GTK_CONTAINER (MenuBar), MenuFile);

  MenuFile_menu = gtk_menu_new ();
  gtk_widget_ref (MenuFile_menu);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuFile_menu", MenuFile_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (MenuFile), MenuFile_menu);
  MenuFile_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (MenuFile_menu));

  MenuFileEdit = gtk_menu_item_new_with_label (_("Edit"));
  gtk_widget_ref (MenuFileEdit);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuFileEdit", MenuFileEdit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuFileEdit);
  gtk_container_add (GTK_CONTAINER (MenuFile_menu), MenuFileEdit);

  MenuFileSave = gtk_menu_item_new_with_label (_("Save"));
  gtk_widget_ref (MenuFileSave);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuFileSave", MenuFileSave,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuFileSave);
  gtk_container_add (GTK_CONTAINER (MenuFile_menu), MenuFileSave);

  MenuFilePrint = gtk_menu_item_new_with_label (_("Print"));
  gtk_widget_ref (MenuFilePrint);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuFilePrint", MenuFilePrint,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuFilePrint);
  gtk_container_add (GTK_CONTAINER (MenuFile_menu), MenuFilePrint);

  MenuFileClose = gtk_menu_item_new_with_label (_("Close"));
  gtk_widget_ref (MenuFileClose);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuFileClose", MenuFileClose,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuFileClose);
  gtk_container_add (GTK_CONTAINER (MenuFile_menu), MenuFileClose);

  MenuFileSeparator1 = gtk_menu_item_new ();
  gtk_widget_ref (MenuFileSeparator1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuFileSeparator1", MenuFileSeparator1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuFileSeparator1);
  gtk_container_add (GTK_CONTAINER (MenuFile_menu), MenuFileSeparator1);
  gtk_widget_set_sensitive (MenuFileSeparator1, FALSE);

  MenuFileNew = gtk_menu_item_new_with_label (_("New"));
  gtk_widget_ref (MenuFileNew);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuFileNew", MenuFileNew,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuFileNew);
  gtk_container_add (GTK_CONTAINER (MenuFile_menu), MenuFileNew);

  MenuFileImport = gtk_menu_item_new_with_label (_("Import"));
  gtk_widget_ref (MenuFileImport);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuFileImport", MenuFileImport,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuFileImport);
  gtk_container_add (GTK_CONTAINER (MenuFile_menu), MenuFileImport);

  MenuFileUnlink = gtk_menu_item_new_with_label (_("Unlink"));
  gtk_widget_ref (MenuFileUnlink);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuFileUnlink", MenuFileUnlink,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuFileUnlink);
  gtk_container_add (GTK_CONTAINER (MenuFile_menu), MenuFileUnlink);

  MenuFileDelete = gtk_menu_item_new_with_label (_("Delete"));
  gtk_widget_ref (MenuFileDelete);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuFileDelete", MenuFileDelete,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuFileDelete);
  gtk_container_add (GTK_CONTAINER (MenuFile_menu), MenuFileDelete);

  MenuAction = gtk_menu_item_new_with_label (_("Action"));
  gtk_widget_ref (MenuAction);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuAction", MenuAction,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuAction);
  gtk_container_add (GTK_CONTAINER (MenuBar), MenuAction);

  MenuTool = gtk_menu_item_new_with_label (_("Tool"));
  gtk_widget_ref (MenuTool);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuTool", MenuTool,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuTool);
  gtk_container_add (GTK_CONTAINER (MenuBar), MenuTool);

  MenuWindow = gtk_menu_item_new_with_label (_("Window"));
  gtk_widget_ref (MenuWindow);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuWindow", MenuWindow,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuWindow);
  gtk_container_add (GTK_CONTAINER (MenuBar), MenuWindow);

  ToolBoxMain = gtk_handle_box_new ();
  gtk_widget_ref (ToolBoxMain);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "ToolBoxMain", ToolBoxMain,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_box_pack_start (GTK_BOX (VBoxMain), ToolBoxMain, TRUE, TRUE, 0);
  gtk_widget_set_usize (ToolBoxMain, -2, 32);
  gtk_widget_set_sensitive (ToolBoxMain, FALSE);

  hboxToolBoxMainContainer = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hboxToolBoxMainContainer);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "hboxToolBoxMainContainer", hboxToolBoxMainContainer,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hboxToolBoxMainContainer);
  gtk_container_add (GTK_CONTAINER (ToolBoxMain), hboxToolBoxMainContainer);

  ToolBoxUser = gtk_handle_box_new ();
  gtk_widget_ref (ToolBoxUser);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "ToolBoxUser", ToolBoxUser,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_box_pack_start (GTK_BOX (VBoxMain), ToolBoxUser, TRUE, TRUE, 0);
  gtk_widget_set_usize (ToolBoxUser, -2, 32);
  gtk_widget_set_sensitive (ToolBoxUser, FALSE);

  ToolBoxClientContainer = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (ToolBoxClientContainer);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "ToolBoxClientContainer", ToolBoxClientContainer,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (ToolBoxClientContainer);
  gtk_container_add (GTK_CONTAINER (ToolBoxUser), ToolBoxClientContainer);

  VBoxWorkArea = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (VBoxWorkArea);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "VBoxWorkArea", VBoxWorkArea,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (VBoxWorkArea);
  gtk_box_pack_start (GTK_BOX (VBoxMain), VBoxWorkArea, TRUE, TRUE, 0);

  vpaned1 = gtk_vpaned_new ();
  gtk_widget_ref (vpaned1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "vpaned1", vpaned1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vpaned1);
  gtk_box_pack_start (GTK_BOX (VBoxWorkArea), vpaned1, TRUE, TRUE, 0);
  gtk_paned_set_position (GTK_PANED (vpaned1), 117);

  HBoxWorkTopArea = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (HBoxWorkTopArea);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "HBoxWorkTopArea", HBoxWorkTopArea,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (HBoxWorkTopArea);
  gtk_paned_pack1 (GTK_PANED (vpaned1), HBoxWorkTopArea, TRUE, TRUE);

  HPaned = gtk_hpaned_new ();
  gtk_widget_ref (HPaned);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "HPaned", HPaned,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (HPaned);
  gtk_box_pack_start (GTK_BOX (HBoxWorkTopArea), HPaned, TRUE, TRUE, 0);
  gtk_paned_set_position (GTK_PANED (HPaned), 200);

  ProjectArea = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (ProjectArea);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "ProjectArea", ProjectArea,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (ProjectArea);
  gtk_paned_pack1 (GTK_PANED (HPaned), ProjectArea, FALSE, FALSE);
  gtk_widget_set_usize (ProjectArea, 150, -2);
  gtk_container_set_border_width (GTK_CONTAINER (ProjectArea), 4);

  DocNotebook = gtk_notebook_new ();
  gtk_widget_ref (DocNotebook);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "DocNotebook", DocNotebook,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (DocNotebook);
  gtk_box_pack_start (GTK_BOX (ProjectArea), DocNotebook, TRUE, TRUE, 0);
  gtk_notebook_set_scrollable (GTK_NOTEBOOK (DocNotebook), TRUE);

  DocModulesWindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (DocModulesWindow);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "DocModulesWindow", DocModulesWindow,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (DocModulesWindow);
  gtk_container_add (GTK_CONTAINER (DocNotebook), DocModulesWindow);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (DocModulesWindow), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  DocModulesTree = gtk_ctree_new (1, 0);
  gtk_widget_ref (DocModulesTree);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "DocModulesTree", DocModulesTree,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (DocModulesTree);
  gtk_container_add (GTK_CONTAINER (DocModulesWindow), DocModulesTree);
  gtk_clist_set_column_width (GTK_CLIST (DocModulesTree), 0, 80);
  gtk_clist_column_titles_hide (GTK_CLIST (DocModulesTree));

  DocModulesLabel = gtk_label_new (_("Modules"));
  gtk_widget_ref (DocModulesLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "DocModulesLabel", DocModulesLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (DocModulesLabel);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (DocNotebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (DocNotebook), 0), DocModulesLabel);

  DocFilesWindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (DocFilesWindow);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "DocFilesWindow", DocFilesWindow,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (DocFilesWindow);
  gtk_container_add (GTK_CONTAINER (DocNotebook), DocFilesWindow);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (DocFilesWindow), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  DocFilesTree = gtk_ctree_new (1, 0);
  gtk_widget_ref (DocFilesTree);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "DocFilesTree", DocFilesTree,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (DocFilesTree);
  gtk_container_add (GTK_CONTAINER (DocFilesWindow), DocFilesTree);
  gtk_clist_set_column_width (GTK_CLIST (DocFilesTree), 0, 80);
  gtk_clist_column_titles_hide (GTK_CLIST (DocFilesTree));

  DocFilesLabel = gtk_label_new (_("Files"));
  gtk_widget_ref (DocFilesLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "DocFilesLabel", DocFilesLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (DocFilesLabel);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (DocNotebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (DocNotebook), 1), DocFilesLabel);

  StatusArea = gtk_notebook_new ();
  gtk_widget_ref (StatusArea);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "StatusArea", StatusArea,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (StatusArea);
  gtk_paned_pack2 (GTK_PANED (vpaned1), StatusArea, TRUE, TRUE);
  gtk_widget_set_usize (StatusArea, -2, 100);
  gtk_container_set_border_width (GTK_CONTAINER (StatusArea), 4);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow2);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "scrolledwindow2", scrolledwindow2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow2);
  gtk_container_add (GTK_CONTAINER (StatusArea), scrolledwindow2);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  StatusText = gtk_text_new (NULL, NULL);
  gtk_widget_ref (StatusText);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "StatusText", StatusText,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (StatusText);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), StatusText);

  StatusLabel = gtk_label_new (_("Status"));
  gtk_widget_ref (StatusLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "StatusLabel", StatusLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (StatusLabel);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (StatusArea), gtk_notebook_get_nth_page (GTK_NOTEBOOK (StatusArea), 0), StatusLabel);

  StatusBar = gtk_statusbar_new ();
  gtk_widget_ref (StatusBar);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "StatusBar", StatusBar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (StatusBar);
  gtk_box_pack_start (GTK_BOX (VBoxMain), StatusBar, FALSE, FALSE, 0);

  gtk_signal_connect (GTK_OBJECT (MainWindow), "delete_event",
                      GTK_SIGNAL_FUNC (on_MainWindow_delete_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (MenuProjectNew), "activate",
                      GTK_SIGNAL_FUNC (ProjectNew_MenuActivation),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (MenuProjectOpen), "activate",
                      GTK_SIGNAL_FUNC (ProjectOpen_MenuActivation),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (MenuProjectProperties), "activate",
                      GTK_SIGNAL_FUNC (ProjectProperties_MenuActivation),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (MenuProjectClose), "activate",
                      GTK_SIGNAL_FUNC (ProjectClose_MenuActivation),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (MenuProjectExit), "activate",
                      GTK_SIGNAL_FUNC (ProjectExit_MenuActivation),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (MenuFileEdit), "activate",
                      GTK_SIGNAL_FUNC (FileEdit_MenuActivation),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (MenuFileSave), "activate",
                      GTK_SIGNAL_FUNC (FileSave_MenuActivation),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (MenuFilePrint), "activate",
                      GTK_SIGNAL_FUNC (FilePrint_MenuActivation),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (MenuFileClose), "activate",
                      GTK_SIGNAL_FUNC (FileClose_MenuActivation),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (MenuFileNew), "activate",
                      GTK_SIGNAL_FUNC (FileNew_MenuActivation),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (MenuFileImport), "activate",
                      GTK_SIGNAL_FUNC (FileImport_MenuActivation),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (MenuFileUnlink), "activate",
                      GTK_SIGNAL_FUNC (FileUnlink_MenuActivation),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (MenuFileDelete), "activate",
                      GTK_SIGNAL_FUNC (FileDelete_MenuActivation),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (DocModulesTree), "tree_select_row",
                      GTK_SIGNAL_FUNC (Doc_Selection),
                      NULL);
  gtk_signal_connect_after (GTK_OBJECT (DocModulesTree), "button_press_event",
                            GTK_SIGNAL_FUNC (on_DocModulesTree_button_press_event),
                            NULL);
  gtk_signal_connect (GTK_OBJECT (DocFilesTree), "tree_select_row",
                      GTK_SIGNAL_FUNC (Doc_Selection),
                      NULL);
  gtk_signal_connect_after (GTK_OBJECT (DocFilesTree), "button_press_event",
                            GTK_SIGNAL_FUNC (on_DocModulesTree_button_press_event),
                            NULL);

  return MainWindow;
}

GtkWidget*
create_ProjectProperties (void)
{
  GtkWidget *ProjectProperties;
  GtkWidget *pProjectProperitesVBox;
  GtkWidget *pProjectPropertiesFrame;
  GtkWidget *pProjectPropertiesTable;
  GtkWidget *pProjectPropertiesLabelName;
  GtkWidget *pProjectPropertiesectoryLabelDir;
  GtkWidget *pProjectPropertiesLabelAuthor;
  GtkWidget *pProjectPropertiesLabelDescription;
  GtkWidget *pProjectPropertiesEntryName;
  GtkWidget *pProjectPropertiesEntryAuthor;
  GtkWidget *pProjectPropertiesScrolledWindow;
  GtkWidget *pProjectPropertiesTextDescription;
  GtkWidget *pProjectPropertiesVSeparator;
  GtkWidget *pProjectPropertiesEntryDir;
  GtkWidget *pProjectPropertiesHBox;
  GtkWidget *pProjectPropertiesButtonOk;
  GtkWidget *pProjectPropertiesButtonCancel;

  ProjectProperties = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (ProjectProperties), "ProjectProperties", ProjectProperties);
  gtk_widget_set_usize (ProjectProperties, 400, 250);
  gtk_window_set_title (GTK_WINDOW (ProjectProperties), _("Project Properties"));
  gtk_window_set_modal (GTK_WINDOW (ProjectProperties), TRUE);
  gtk_window_set_default_size (GTK_WINDOW (ProjectProperties), 400, 250);
  gtk_window_set_policy (GTK_WINDOW (ProjectProperties), FALSE, FALSE, FALSE);

  pProjectProperitesVBox = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (pProjectProperitesVBox);
  gtk_object_set_data_full (GTK_OBJECT (ProjectProperties), "pProjectProperitesVBox", pProjectProperitesVBox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pProjectProperitesVBox);
  gtk_container_add (GTK_CONTAINER (ProjectProperties), pProjectProperitesVBox);

  pProjectPropertiesFrame = gtk_frame_new (_("Project"));
  gtk_widget_ref (pProjectPropertiesFrame);
  gtk_object_set_data_full (GTK_OBJECT (ProjectProperties), "pProjectPropertiesFrame", pProjectPropertiesFrame,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pProjectPropertiesFrame);
  gtk_box_pack_start (GTK_BOX (pProjectProperitesVBox), pProjectPropertiesFrame, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (pProjectPropertiesFrame), 8);

  pProjectPropertiesTable = gtk_table_new (5, 2, FALSE);
  gtk_widget_ref (pProjectPropertiesTable);
  gtk_object_set_data_full (GTK_OBJECT (ProjectProperties), "pProjectPropertiesTable", pProjectPropertiesTable,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pProjectPropertiesTable);
  gtk_container_add (GTK_CONTAINER (pProjectPropertiesFrame), pProjectPropertiesTable);
  gtk_container_set_border_width (GTK_CONTAINER (pProjectPropertiesTable), 8);
  gtk_table_set_row_spacings (GTK_TABLE (pProjectPropertiesTable), 4);
  gtk_table_set_col_spacings (GTK_TABLE (pProjectPropertiesTable), 8);

  pProjectPropertiesLabelName = gtk_label_new (_("Name"));
  gtk_widget_ref (pProjectPropertiesLabelName);
  gtk_object_set_data_full (GTK_OBJECT (ProjectProperties), "pProjectPropertiesLabelName", pProjectPropertiesLabelName,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pProjectPropertiesLabelName);
  gtk_table_attach (GTK_TABLE (pProjectPropertiesTable), pProjectPropertiesLabelName, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (pProjectPropertiesLabelName), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (pProjectPropertiesLabelName), 0, 0.5);

  pProjectPropertiesectoryLabelDir = gtk_label_new (_("Directory"));
  gtk_widget_ref (pProjectPropertiesectoryLabelDir);
  gtk_object_set_data_full (GTK_OBJECT (ProjectProperties), "pProjectPropertiesectoryLabelDir", pProjectPropertiesectoryLabelDir,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pProjectPropertiesectoryLabelDir);
  gtk_table_attach (GTK_TABLE (pProjectPropertiesTable), pProjectPropertiesectoryLabelDir, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (pProjectPropertiesectoryLabelDir), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (pProjectPropertiesectoryLabelDir), 0, 0.5);

  pProjectPropertiesLabelAuthor = gtk_label_new (_("Author"));
  gtk_widget_ref (pProjectPropertiesLabelAuthor);
  gtk_object_set_data_full (GTK_OBJECT (ProjectProperties), "pProjectPropertiesLabelAuthor", pProjectPropertiesLabelAuthor,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pProjectPropertiesLabelAuthor);
  gtk_table_attach (GTK_TABLE (pProjectPropertiesTable), pProjectPropertiesLabelAuthor, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (pProjectPropertiesLabelAuthor), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (pProjectPropertiesLabelAuthor), 0, 0.5);

  pProjectPropertiesLabelDescription = gtk_label_new (_("Description"));
  gtk_widget_ref (pProjectPropertiesLabelDescription);
  gtk_object_set_data_full (GTK_OBJECT (ProjectProperties), "pProjectPropertiesLabelDescription", pProjectPropertiesLabelDescription,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pProjectPropertiesLabelDescription);
  gtk_table_attach (GTK_TABLE (pProjectPropertiesTable), pProjectPropertiesLabelDescription, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (pProjectPropertiesLabelDescription), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (pProjectPropertiesLabelDescription), 0, 0);

  pProjectPropertiesEntryName = gtk_entry_new ();
  gtk_widget_ref (pProjectPropertiesEntryName);
  gtk_object_set_data_full (GTK_OBJECT (ProjectProperties), "pProjectPropertiesEntryName", pProjectPropertiesEntryName,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pProjectPropertiesEntryName);
  gtk_table_attach (GTK_TABLE (pProjectPropertiesTable), pProjectPropertiesEntryName, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_SET_FLAGS (pProjectPropertiesEntryName, GTK_CAN_DEFAULT);

  pProjectPropertiesEntryAuthor = gtk_entry_new ();
  gtk_widget_ref (pProjectPropertiesEntryAuthor);
  gtk_object_set_data_full (GTK_OBJECT (ProjectProperties), "pProjectPropertiesEntryAuthor", pProjectPropertiesEntryAuthor,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pProjectPropertiesEntryAuthor);
  gtk_table_attach (GTK_TABLE (pProjectPropertiesTable), pProjectPropertiesEntryAuthor, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_SET_FLAGS (pProjectPropertiesEntryAuthor, GTK_CAN_DEFAULT);

  pProjectPropertiesScrolledWindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (pProjectPropertiesScrolledWindow);
  gtk_object_set_data_full (GTK_OBJECT (ProjectProperties), "pProjectPropertiesScrolledWindow", pProjectPropertiesScrolledWindow,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pProjectPropertiesScrolledWindow);
  gtk_table_attach (GTK_TABLE (pProjectPropertiesTable), pProjectPropertiesScrolledWindow, 1, 2, 3, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 0, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (pProjectPropertiesScrolledWindow), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  pProjectPropertiesTextDescription = gtk_text_new (NULL, NULL);
  gtk_widget_ref (pProjectPropertiesTextDescription);
  gtk_object_set_data_full (GTK_OBJECT (ProjectProperties), "pProjectPropertiesTextDescription", pProjectPropertiesTextDescription,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pProjectPropertiesTextDescription);
  gtk_container_add (GTK_CONTAINER (pProjectPropertiesScrolledWindow), pProjectPropertiesTextDescription);
  GTK_WIDGET_SET_FLAGS (pProjectPropertiesTextDescription, GTK_CAN_DEFAULT);
  gtk_text_set_editable (GTK_TEXT (pProjectPropertiesTextDescription), TRUE);

  pProjectPropertiesVSeparator = gtk_vseparator_new ();
  gtk_widget_ref (pProjectPropertiesVSeparator);
  gtk_object_set_data_full (GTK_OBJECT (ProjectProperties), "pProjectPropertiesVSeparator", pProjectPropertiesVSeparator,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_table_attach (GTK_TABLE (pProjectPropertiesTable), pProjectPropertiesVSeparator, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_widget_set_sensitive (pProjectPropertiesVSeparator, FALSE);

  pProjectPropertiesEntryDir = gtk_entry_new ();
  gtk_widget_ref (pProjectPropertiesEntryDir);
  gtk_object_set_data_full (GTK_OBJECT (ProjectProperties), "pProjectPropertiesEntryDir", pProjectPropertiesEntryDir,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pProjectPropertiesEntryDir);
  gtk_table_attach (GTK_TABLE (pProjectPropertiesTable), pProjectPropertiesEntryDir, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_SET_FLAGS (pProjectPropertiesEntryDir, GTK_CAN_DEFAULT);

  pProjectPropertiesHBox = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (pProjectPropertiesHBox);
  gtk_object_set_data_full (GTK_OBJECT (ProjectProperties), "pProjectPropertiesHBox", pProjectPropertiesHBox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pProjectPropertiesHBox);
  gtk_box_pack_start (GTK_BOX (pProjectProperitesVBox), pProjectPropertiesHBox, FALSE, FALSE, 0);
  gtk_widget_set_usize (pProjectPropertiesHBox, -2, 48);
  gtk_container_set_border_width (GTK_CONTAINER (pProjectPropertiesHBox), 8);

  pProjectPropertiesButtonOk = gtk_button_new_with_label (_("Ok"));
  gtk_widget_ref (pProjectPropertiesButtonOk);
  gtk_object_set_data_full (GTK_OBJECT (ProjectProperties), "pProjectPropertiesButtonOk", pProjectPropertiesButtonOk,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pProjectPropertiesButtonOk);
  gtk_box_pack_start (GTK_BOX (pProjectPropertiesHBox), pProjectPropertiesButtonOk, FALSE, FALSE, 0);
  gtk_widget_set_usize (pProjectPropertiesButtonOk, 112, 48);
  GTK_WIDGET_SET_FLAGS (pProjectPropertiesButtonOk, GTK_CAN_DEFAULT);

  pProjectPropertiesButtonCancel = gtk_button_new_with_label (_("Cancel"));
  gtk_widget_ref (pProjectPropertiesButtonCancel);
  gtk_object_set_data_full (GTK_OBJECT (ProjectProperties), "pProjectPropertiesButtonCancel", pProjectPropertiesButtonCancel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pProjectPropertiesButtonCancel);
  gtk_box_pack_start (GTK_BOX (pProjectPropertiesHBox), pProjectPropertiesButtonCancel, FALSE, FALSE, 0);
  gtk_widget_set_usize (pProjectPropertiesButtonCancel, 112, 48);
  GTK_WIDGET_SET_FLAGS (pProjectPropertiesButtonCancel, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (ProjectProperties), "delete_event",
                      GTK_SIGNAL_FUNC (ProjectProperties_ButtonClicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pProjectPropertiesEntryName), "changed",
                      GTK_SIGNAL_FUNC (ProjectProperties_NameChanged),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pProjectPropertiesEntryDir), "delete_text",
                      GTK_SIGNAL_FUNC (ProjectProperties_DirChanged),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pProjectPropertiesEntryDir), "insert_text",
                      GTK_SIGNAL_FUNC (ProjectProperties_DirChanged),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pProjectPropertiesButtonOk), "clicked",
                      GTK_SIGNAL_FUNC (ProjectProperties_ButtonClicked),
                      GTK_OBJECT(pProjectPropertiesButtonOk));
  gtk_signal_connect (GTK_OBJECT (pProjectPropertiesButtonCancel), "clicked",
                      GTK_SIGNAL_FUNC (ProjectProperties_ButtonClicked),
                      GTK_OBJECT(pProjectPropertiesButtonCancel));

  gtk_widget_grab_focus (pProjectPropertiesButtonOk);
  gtk_widget_grab_default (pProjectPropertiesEntryName);
  return ProjectProperties;
}

GtkWidget*
create_FileNew (void)
{
  GtkWidget *FileNew;
  GtkWidget *pFileNewVBox;
  GtkWidget *pFileNewFrame;
  GtkWidget *pFileNewTable;
  GtkWidget *pFileNewTypeCombo;
  GtkWidget *pFileNewTypeComboEntry;
  GtkWidget *pFileNewNameEntry;
  GtkWidget *pFileNewTypeLabel;
  GtkWidget *pFileNewNameLabel;
  GtkWidget *pFileNewHBox;
  GtkWidget *pFileNewButtonOk;
  GtkWidget *pFileNewButtonCancel;

  FileNew = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (FileNew), "FileNew", FileNew);
  gtk_widget_set_usize (FileNew, 400, -2);
  gtk_window_set_title (GTK_WINDOW (FileNew), _("New file ..."));
  gtk_window_set_modal (GTK_WINDOW (FileNew), TRUE);
  gtk_window_set_default_size (GTK_WINDOW (FileNew), 400, -1);
  gtk_window_set_policy (GTK_WINDOW (FileNew), FALSE, FALSE, FALSE);

  pFileNewVBox = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (pFileNewVBox);
  gtk_object_set_data_full (GTK_OBJECT (FileNew), "pFileNewVBox", pFileNewVBox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pFileNewVBox);
  gtk_container_add (GTK_CONTAINER (FileNew), pFileNewVBox);

  pFileNewFrame = gtk_frame_new (_("File"));
  gtk_widget_ref (pFileNewFrame);
  gtk_object_set_data_full (GTK_OBJECT (FileNew), "pFileNewFrame", pFileNewFrame,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pFileNewFrame);
  gtk_box_pack_start (GTK_BOX (pFileNewVBox), pFileNewFrame, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (pFileNewFrame), 8);

  pFileNewTable = gtk_table_new (2, 2, FALSE);
  gtk_widget_ref (pFileNewTable);
  gtk_object_set_data_full (GTK_OBJECT (FileNew), "pFileNewTable", pFileNewTable,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pFileNewTable);
  gtk_container_add (GTK_CONTAINER (pFileNewFrame), pFileNewTable);
  gtk_container_set_border_width (GTK_CONTAINER (pFileNewTable), 8);
  gtk_table_set_row_spacings (GTK_TABLE (pFileNewTable), 4);
  gtk_table_set_col_spacings (GTK_TABLE (pFileNewTable), 8);

  pFileNewTypeCombo = gtk_combo_new ();
  gtk_widget_ref (pFileNewTypeCombo);
  gtk_object_set_data_full (GTK_OBJECT (FileNew), "pFileNewTypeCombo", pFileNewTypeCombo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pFileNewTypeCombo);
  gtk_table_attach (GTK_TABLE (pFileNewTable), pFileNewTypeCombo, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_SET_FLAGS (pFileNewTypeCombo, GTK_CAN_DEFAULT);

  pFileNewTypeComboEntry = GTK_COMBO (pFileNewTypeCombo)->entry;
  gtk_widget_ref (pFileNewTypeComboEntry);
  gtk_object_set_data_full (GTK_OBJECT (FileNew), "pFileNewTypeComboEntry", pFileNewTypeComboEntry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pFileNewTypeComboEntry);
  gtk_entry_set_editable (GTK_ENTRY (pFileNewTypeComboEntry), FALSE);

  pFileNewNameEntry = gtk_entry_new ();
  gtk_widget_ref (pFileNewNameEntry);
  gtk_object_set_data_full (GTK_OBJECT (FileNew), "pFileNewNameEntry", pFileNewNameEntry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pFileNewNameEntry);
  gtk_table_attach (GTK_TABLE (pFileNewTable), pFileNewNameEntry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_SET_FLAGS (pFileNewNameEntry, GTK_CAN_DEFAULT);

  pFileNewTypeLabel = gtk_label_new (_("Type"));
  gtk_widget_ref (pFileNewTypeLabel);
  gtk_object_set_data_full (GTK_OBJECT (FileNew), "pFileNewTypeLabel", pFileNewTypeLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pFileNewTypeLabel);
  gtk_table_attach (GTK_TABLE (pFileNewTable), pFileNewTypeLabel, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pFileNewTypeLabel), 0, 0.5);

  pFileNewNameLabel = gtk_label_new (_("Name"));
  gtk_widget_ref (pFileNewNameLabel);
  gtk_object_set_data_full (GTK_OBJECT (FileNew), "pFileNewNameLabel", pFileNewNameLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pFileNewNameLabel);
  gtk_table_attach (GTK_TABLE (pFileNewTable), pFileNewNameLabel, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pFileNewNameLabel), 0, 0.5);

  pFileNewHBox = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (pFileNewHBox);
  gtk_object_set_data_full (GTK_OBJECT (FileNew), "pFileNewHBox", pFileNewHBox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pFileNewHBox);
  gtk_box_pack_start (GTK_BOX (pFileNewVBox), pFileNewHBox, FALSE, FALSE, 0);
  gtk_widget_set_usize (pFileNewHBox, -2, 48);
  gtk_container_set_border_width (GTK_CONTAINER (pFileNewHBox), 8);

  pFileNewButtonOk = gtk_button_new_with_label (_("Ok"));
  gtk_widget_ref (pFileNewButtonOk);
  gtk_object_set_data_full (GTK_OBJECT (FileNew), "pFileNewButtonOk", pFileNewButtonOk,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pFileNewButtonOk);
  gtk_box_pack_start (GTK_BOX (pFileNewHBox), pFileNewButtonOk, FALSE, FALSE, 0);
  gtk_widget_set_usize (pFileNewButtonOk, 112, 48);
  GTK_WIDGET_SET_FLAGS (pFileNewButtonOk, GTK_CAN_DEFAULT);

  pFileNewButtonCancel = gtk_button_new_with_label (_("Cancel"));
  gtk_widget_ref (pFileNewButtonCancel);
  gtk_object_set_data_full (GTK_OBJECT (FileNew), "pFileNewButtonCancel", pFileNewButtonCancel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pFileNewButtonCancel);
  gtk_box_pack_start (GTK_BOX (pFileNewHBox), pFileNewButtonCancel, FALSE, FALSE, 0);
  gtk_widget_set_usize (pFileNewButtonCancel, 112, 48);
  GTK_WIDGET_SET_FLAGS (pFileNewButtonCancel, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (FileNew), "destroy_event",
                      GTK_SIGNAL_FUNC (FileNew_Destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pFileNewButtonOk), "clicked",
                      GTK_SIGNAL_FUNC (FileNew_ButtonOk),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pFileNewButtonCancel), "clicked",
                      GTK_SIGNAL_FUNC (FileNew_ButtonCancel),
                      NULL);

  gtk_widget_grab_focus (pFileNewNameEntry);
  gtk_widget_grab_default (pFileNewNameEntry);
  return FileNew;
}

