/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_MainWindow (void)
{
  GtkWidget *MainWindow;
  GtkWidget *VBoxMain;
  GtkWidget *MenuBar;
  GtkWidget *MenuProject;
  GtkWidget *MenuProject_menu;
  GtkAccelGroup *MenuProject_menu_accels;
  GtkWidget *MenuProjectNew;
  GtkWidget *MenuProjectOpen;
  GtkWidget *MenuProjectSave;
  GtkWidget *MenuProjectClose;
  GtkWidget *MenuProjectSeparator1;
  GtkWidget *MenuProjectExit;
  GtkWidget *MenuFile;
  GtkWidget *MenuFile_menu;
  GtkAccelGroup *MenuFile_menu_accels;
  GtkWidget *MenuFileEdit;
  GtkWidget *MenuFileSave;
  GtkWidget *MenuFilePrint;
  GtkWidget *MenuFileClose;
  GtkWidget *MenuFileSeparator1;
  GtkWidget *MenuFileNew;
  GtkWidget *MenuFileImport;
  GtkWidget *MenuFileUnlink;
  GtkWidget *MenuFileDelete;
  GtkWidget *MenuAction;
  GtkWidget *MenuTool;
  GtkWidget *MenuWindow;
  GtkWidget *ToolBoxMain;
  GtkWidget *hboxToolBoxMainContainer;
  GtkWidget *ToolBoxUser;
  GtkWidget *ToolBoxClientContainer;
  GtkWidget *VBoxWorkArea;
  GtkWidget *vpaned1;
  GtkWidget *HBoxWorkTopArea;
  GtkWidget *HPaned;
  GtkWidget *ProjectArea;
  GtkWidget *DocNotebook;
  GtkWidget *DocModulesWindow;
  GtkWidget *DocModulesTree;
  GtkWidget *DocModulesLabel;
  GtkWidget *DocFilesWindow;
  GtkWidget *DocFilesTree;
  GtkWidget *DocFilesLabel;
  GtkWidget *StatusArea;
  GtkWidget *scrolledwindow2;
  GtkWidget *StatusText;
  GtkWidget *StatusLabel;
  GtkWidget *StatusBar;

  MainWindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (MainWindow), "MainWindow", MainWindow);
  gtk_window_set_title (GTK_WINDOW (MainWindow), _("gEDA"));
  gtk_window_set_position (GTK_WINDOW (MainWindow), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (MainWindow), 510, 300);

  VBoxMain = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (VBoxMain);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "VBoxMain", VBoxMain,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (VBoxMain);
  gtk_container_add (GTK_CONTAINER (MainWindow), VBoxMain);

  MenuBar = gtk_menu_bar_new ();
  gtk_widget_ref (MenuBar);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuBar", MenuBar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuBar);
  gtk_box_pack_start (GTK_BOX (VBoxMain), MenuBar, FALSE, FALSE, 0);

  MenuProject = gtk_menu_item_new_with_label (_("Project"));
  gtk_widget_ref (MenuProject);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuProject", MenuProject,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuProject);
  gtk_container_add (GTK_CONTAINER (MenuBar), MenuProject);

  MenuProject_menu = gtk_menu_new ();
  gtk_widget_ref (MenuProject_menu);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuProject_menu", MenuProject_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (MenuProject), MenuProject_menu);
  MenuProject_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (MenuProject_menu));

  MenuProjectNew = gtk_menu_item_new_with_label (_("New"));
  gtk_widget_ref (MenuProjectNew);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuProjectNew", MenuProjectNew,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuProjectNew);
  gtk_container_add (GTK_CONTAINER (MenuProject_menu), MenuProjectNew);

  MenuProjectOpen = gtk_menu_item_new_with_label (_("Open"));
  gtk_widget_ref (MenuProjectOpen);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuProjectOpen", MenuProjectOpen,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuProjectOpen);
  gtk_container_add (GTK_CONTAINER (MenuProject_menu), MenuProjectOpen);

  MenuProjectSave = gtk_menu_item_new_with_label (_("Save"));
  gtk_widget_ref (MenuProjectSave);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuProjectSave", MenuProjectSave,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuProjectSave);
  gtk_container_add (GTK_CONTAINER (MenuProject_menu), MenuProjectSave);

  MenuProjectClose = gtk_menu_item_new_with_label (_("Close"));
  gtk_widget_ref (MenuProjectClose);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuProjectClose", MenuProjectClose,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuProjectClose);
  gtk_container_add (GTK_CONTAINER (MenuProject_menu), MenuProjectClose);

  MenuProjectSeparator1 = gtk_menu_item_new ();
  gtk_widget_ref (MenuProjectSeparator1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuProjectSeparator1", MenuProjectSeparator1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuProjectSeparator1);
  gtk_container_add (GTK_CONTAINER (MenuProject_menu), MenuProjectSeparator1);
  gtk_widget_set_sensitive (MenuProjectSeparator1, FALSE);

  MenuProjectExit = gtk_menu_item_new_with_label (_("Exit"));
  gtk_widget_ref (MenuProjectExit);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuProjectExit", MenuProjectExit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuProjectExit);
  gtk_container_add (GTK_CONTAINER (MenuProject_menu), MenuProjectExit);

  MenuFile = gtk_menu_item_new_with_label (_("File"));
  gtk_widget_ref (MenuFile);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuFile", MenuFile,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuFile);
  gtk_container_add (GTK_CONTAINER (MenuBar), MenuFile);

  MenuFile_menu = gtk_menu_new ();
  gtk_widget_ref (MenuFile_menu);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuFile_menu", MenuFile_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (MenuFile), MenuFile_menu);
  MenuFile_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (MenuFile_menu));

  MenuFileEdit = gtk_menu_item_new_with_label (_("Edit"));
  gtk_widget_ref (MenuFileEdit);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuFileEdit", MenuFileEdit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuFileEdit);
  gtk_container_add (GTK_CONTAINER (MenuFile_menu), MenuFileEdit);

  MenuFileSave = gtk_menu_item_new_with_label (_("Save"));
  gtk_widget_ref (MenuFileSave);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuFileSave", MenuFileSave,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuFileSave);
  gtk_container_add (GTK_CONTAINER (MenuFile_menu), MenuFileSave);

  MenuFilePrint = gtk_menu_item_new_with_label (_("Print"));
  gtk_widget_ref (MenuFilePrint);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuFilePrint", MenuFilePrint,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuFilePrint);
  gtk_container_add (GTK_CONTAINER (MenuFile_menu), MenuFilePrint);

  MenuFileClose = gtk_menu_item_new_with_label (_("Close"));
  gtk_widget_ref (MenuFileClose);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuFileClose", MenuFileClose,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuFileClose);
  gtk_container_add (GTK_CONTAINER (MenuFile_menu), MenuFileClose);

  MenuFileSeparator1 = gtk_menu_item_new ();
  gtk_widget_ref (MenuFileSeparator1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuFileSeparator1", MenuFileSeparator1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuFileSeparator1);
  gtk_container_add (GTK_CONTAINER (MenuFile_menu), MenuFileSeparator1);
  gtk_widget_set_sensitive (MenuFileSeparator1, FALSE);

  MenuFileNew = gtk_menu_item_new_with_label (_("New"));
  gtk_widget_ref (MenuFileNew);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuFileNew", MenuFileNew,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuFileNew);
  gtk_container_add (GTK_CONTAINER (MenuFile_menu), MenuFileNew);

  MenuFileImport = gtk_menu_item_new_with_label (_("Import"));
  gtk_widget_ref (MenuFileImport);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuFileImport", MenuFileImport,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuFileImport);
  gtk_container_add (GTK_CONTAINER (MenuFile_menu), MenuFileImport);

  MenuFileUnlink = gtk_menu_item_new_with_label (_("Unlink"));
  gtk_widget_ref (MenuFileUnlink);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuFileUnlink", MenuFileUnlink,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuFileUnlink);
  gtk_container_add (GTK_CONTAINER (MenuFile_menu), MenuFileUnlink);

  MenuFileDelete = gtk_menu_item_new_with_label (_("Delete"));
  gtk_widget_ref (MenuFileDelete);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuFileDelete", MenuFileDelete,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuFileDelete);
  gtk_container_add (GTK_CONTAINER (MenuFile_menu), MenuFileDelete);

  MenuAction = gtk_menu_item_new_with_label (_("Action"));
  gtk_widget_ref (MenuAction);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuAction", MenuAction,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuAction);
  gtk_container_add (GTK_CONTAINER (MenuBar), MenuAction);

  MenuTool = gtk_menu_item_new_with_label (_("Tool"));
  gtk_widget_ref (MenuTool);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuTool", MenuTool,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuTool);
  gtk_container_add (GTK_CONTAINER (MenuBar), MenuTool);

  MenuWindow = gtk_menu_item_new_with_label (_("Window"));
  gtk_widget_ref (MenuWindow);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "MenuWindow", MenuWindow,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MenuWindow);
  gtk_container_add (GTK_CONTAINER (MenuBar), MenuWindow);

  ToolBoxMain = gtk_handle_box_new ();
  gtk_widget_ref (ToolBoxMain);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "ToolBoxMain", ToolBoxMain,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_box_pack_start (GTK_BOX (VBoxMain), ToolBoxMain, TRUE, TRUE, 0);
  gtk_widget_set_usize (ToolBoxMain, -2, 32);

  hboxToolBoxMainContainer = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hboxToolBoxMainContainer);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "hboxToolBoxMainContainer", hboxToolBoxMainContainer,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hboxToolBoxMainContainer);
  gtk_container_add (GTK_CONTAINER (ToolBoxMain), hboxToolBoxMainContainer);

  ToolBoxUser = gtk_handle_box_new ();
  gtk_widget_ref (ToolBoxUser);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "ToolBoxUser", ToolBoxUser,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_box_pack_start (GTK_BOX (VBoxMain), ToolBoxUser, TRUE, TRUE, 0);
  gtk_widget_set_usize (ToolBoxUser, -2, 32);

  ToolBoxClientContainer = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (ToolBoxClientContainer);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "ToolBoxClientContainer", ToolBoxClientContainer,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (ToolBoxClientContainer);
  gtk_container_add (GTK_CONTAINER (ToolBoxUser), ToolBoxClientContainer);

  VBoxWorkArea = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (VBoxWorkArea);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "VBoxWorkArea", VBoxWorkArea,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (VBoxWorkArea);
  gtk_box_pack_start (GTK_BOX (VBoxMain), VBoxWorkArea, TRUE, TRUE, 0);

  vpaned1 = gtk_vpaned_new ();
  gtk_widget_ref (vpaned1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "vpaned1", vpaned1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vpaned1);
  gtk_box_pack_start (GTK_BOX (VBoxWorkArea), vpaned1, TRUE, TRUE, 0);
  gtk_paned_set_position (GTK_PANED (vpaned1), 117);

  HBoxWorkTopArea = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (HBoxWorkTopArea);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "HBoxWorkTopArea", HBoxWorkTopArea,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (HBoxWorkTopArea);
  gtk_paned_pack1 (GTK_PANED (vpaned1), HBoxWorkTopArea, TRUE, TRUE);

  HPaned = gtk_hpaned_new ();
  gtk_widget_ref (HPaned);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "HPaned", HPaned,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (HPaned);
  gtk_box_pack_start (GTK_BOX (HBoxWorkTopArea), HPaned, TRUE, TRUE, 0);
  gtk_paned_set_position (GTK_PANED (HPaned), 200);

  ProjectArea = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (ProjectArea);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "ProjectArea", ProjectArea,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (ProjectArea);
  gtk_paned_pack1 (GTK_PANED (HPaned), ProjectArea, FALSE, FALSE);
  gtk_widget_set_usize (ProjectArea, 150, -2);
  gtk_container_set_border_width (GTK_CONTAINER (ProjectArea), 4);

  DocNotebook = gtk_notebook_new ();
  gtk_widget_ref (DocNotebook);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "DocNotebook", DocNotebook,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (DocNotebook);
  gtk_box_pack_start (GTK_BOX (ProjectArea), DocNotebook, TRUE, TRUE, 0);
  gtk_notebook_set_scrollable (GTK_NOTEBOOK (DocNotebook), TRUE);

  DocModulesWindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (DocModulesWindow);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "DocModulesWindow", DocModulesWindow,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (DocModulesWindow);
  gtk_container_add (GTK_CONTAINER (DocNotebook), DocModulesWindow);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (DocModulesWindow), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  DocModulesTree = gtk_ctree_new (1, 0);
  gtk_widget_ref (DocModulesTree);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "DocModulesTree", DocModulesTree,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (DocModulesTree);
  gtk_container_add (GTK_CONTAINER (DocModulesWindow), DocModulesTree);
  gtk_clist_set_column_width (GTK_CLIST (DocModulesTree), 0, 80);
  gtk_clist_column_titles_hide (GTK_CLIST (DocModulesTree));

  DocModulesLabel = gtk_label_new (_("Modules"));
  gtk_widget_ref (DocModulesLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "DocModulesLabel", DocModulesLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (DocModulesLabel);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (DocNotebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (DocNotebook), 0), DocModulesLabel);

  DocFilesWindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (DocFilesWindow);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "DocFilesWindow", DocFilesWindow,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (DocFilesWindow);
  gtk_container_add (GTK_CONTAINER (DocNotebook), DocFilesWindow);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (DocFilesWindow), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  DocFilesTree = gtk_ctree_new (1, 0);
  gtk_widget_ref (DocFilesTree);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "DocFilesTree", DocFilesTree,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (DocFilesTree);
  gtk_container_add (GTK_CONTAINER (DocFilesWindow), DocFilesTree);
  gtk_clist_set_column_width (GTK_CLIST (DocFilesTree), 0, 80);
  gtk_clist_column_titles_hide (GTK_CLIST (DocFilesTree));

  DocFilesLabel = gtk_label_new (_("Files"));
  gtk_widget_ref (DocFilesLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "DocFilesLabel", DocFilesLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (DocFilesLabel);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (DocNotebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (DocNotebook), 1), DocFilesLabel);

  StatusArea = gtk_notebook_new ();
  gtk_widget_ref (StatusArea);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "StatusArea", StatusArea,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (StatusArea);
  gtk_paned_pack2 (GTK_PANED (vpaned1), StatusArea, TRUE, TRUE);
  gtk_widget_set_usize (StatusArea, -2, 100);
  gtk_container_set_border_width (GTK_CONTAINER (StatusArea), 4);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow2);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "scrolledwindow2", scrolledwindow2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow2);
  gtk_container_add (GTK_CONTAINER (StatusArea), scrolledwindow2);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  StatusText = gtk_text_new (NULL, NULL);
  gtk_widget_ref (StatusText);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "StatusText", StatusText,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (StatusText);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), StatusText);

  StatusLabel = gtk_label_new (_("Status"));
  gtk_widget_ref (StatusLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "StatusLabel", StatusLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (StatusLabel);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (StatusArea), gtk_notebook_get_nth_page (GTK_NOTEBOOK (StatusArea), 0), StatusLabel);

  StatusBar = gtk_statusbar_new ();
  gtk_widget_ref (StatusBar);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "StatusBar", StatusBar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (StatusBar);
  gtk_box_pack_start (GTK_BOX (VBoxMain), StatusBar, FALSE, FALSE, 0);

  gtk_signal_connect (GTK_OBJECT (MainWindow), "delete_event",
                      GTK_SIGNAL_FUNC (on_MainWindow_delete_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (MenuProjectNew), "activate",
                      GTK_SIGNAL_FUNC (MenuProjectNew_Activation),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (MenuProjectOpen), "activate",
                      GTK_SIGNAL_FUNC (MenuProjectOpen_Activation),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (MenuProjectSave), "activate",
                      GTK_SIGNAL_FUNC (MenuProjectSave_Activation),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (MenuProjectClose), "activate",
                      GTK_SIGNAL_FUNC (MenuProjectClose_Activation),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (MenuProjectExit), "activate",
                      GTK_SIGNAL_FUNC (MenuProjectExit_Activation),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (MenuFileEdit), "activate",
                      GTK_SIGNAL_FUNC (MenuFileEdit_Activation),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (MenuFileSave), "activate",
                      GTK_SIGNAL_FUNC (MenuFileSave_Activation),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (MenuFilePrint), "activate",
                      GTK_SIGNAL_FUNC (MenuFilePrint_Activation),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (MenuFileClose), "activate",
                      GTK_SIGNAL_FUNC (MenuFileClose_Activation),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (MenuFileImport), "activate",
                      GTK_SIGNAL_FUNC (MenuFileImport_Activation),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (MenuFileUnlink), "activate",
                      GTK_SIGNAL_FUNC (MenuFileUnlink_Activation),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (MenuFileDelete), "activate",
                      GTK_SIGNAL_FUNC (MenuFileDelete_Activation),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (DocModulesTree), "tree_select_row",
                      GTK_SIGNAL_FUNC (Doc_Selection),
                      NULL);
  gtk_signal_connect_after (GTK_OBJECT (DocModulesTree), "button_press_event",
                            GTK_SIGNAL_FUNC (on_DocModulesTree_button_press_event),
                            NULL);
  gtk_signal_connect (GTK_OBJECT (DocFilesTree), "tree_select_row",
                      GTK_SIGNAL_FUNC (Doc_Selection),
                      NULL);
  gtk_signal_connect_after (GTK_OBJECT (DocFilesTree), "button_press_event",
                            GTK_SIGNAL_FUNC (on_DocModulesTree_button_press_event),
                            NULL);

  return MainWindow;
}

