/*******************************************************************************/
/*                                                                             */
/* gEDA Suite Project Manager                                                  */
/*                                                                             */
/* Copyright (C) 2002 Piotr Miarecki, sp9rve@eter.ariadna.pl                   */
/*                                                                             */
/* This program is free software; you can redistribute it and/or               */
/* modify it under the terms of the GNU General Public License                 */
/* as published by the Free Software Foundation version 2.                     */
/*                                                                             */
/* This program is distributed in the hope that it will be useful,             */
/* but WITHOUT ANY WARRANTY; without even the implied warranty of              */
/* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               */
/* GNU General Public License for more details.                                */
/*                                                                             */
/* You should have received a copy of the GNU General Public License           */
/* along with this program; if not, write to the Free Software                 */
/* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. */
/*                                                                             */
/*******************************************************************************/

/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif
#include <gtk/gtk.h>
#include <libintl.h>
#include "global.h"
#include "interface.h"
#include "msgbox.h"
#include "project.h"
#include "tool.h"
#include "window.h"



/* registered windows */
GtkWidget *pWindowMain = NULL;

/* running flag */
int bRunning = TRUE;



/*
	Main application function
*/

int main(int argc, char *argv[])
{
	int iResult;

#ifdef ENABLE_NLS
	bindtextdomain (PACKAGE, PACKAGE_LOCALE_DIR);
	textdomain (PACKAGE);
#endif
	gtk_set_locale ();
	gtk_init (&argc, &argv);
#if 0
	add_pixmap_directory (PACKAGE_DATA_DIR "/pixmaps");
	add_pixmap_directory (PACKAGE_SOURCE_DIR "/pixmaps");
#endif
	
	/* create windows */
 	pWindowMain = create_MainWindow();
	gtk_window_set_title(GTK_WINDOW(pWindowMain), GEDA_TITLE);
	gtk_widget_show(pWindowMain);

	/* initializing modules */
	WindowInitialize();
	iResult = ToolInitialize();
	if (iResult != SUCCESS)
	{
		MsgBox("Cannot initialize tool list !", MSGBOX_OK);
		gtk_main_quit();
		return -1;
	}
	ProjectInitialize();
	DocViewInitialize();
	TaskInitialize();
   
	/* main loop */
	while (bRunning != FALSE)
	{
		TaskProcess();
		
		/* refreshing Gtk widgets */
		while (g_main_iteration(FALSE));
	}

	/* releasing */
#if 0	
	iResult = ToolRelease();
	if (iResult != SUCCESS)
	{
		/* TODO: error handling */
	}
#endif
	return 0;
}

