#! /bin/sh

usage ()
{
  cat <<EOF
Usage: lepton-schdiff old new

View a graphical diff of Lepton EDA schematics using lepton-schematic and ImageMagick.

Usage with git:
  git difftool -x lepton-schdiff ...

Usage with Mercurial:
  Add the following to .hgrc:

    [extensions]
    hgext.extdiff =
    [extdiff]
    cmd.schdiff = /path/to/lepton-schdiff

  Then use: hg schdiff ...

Usage with Subversion:
  svn diff --diff-cmd lepton-schdiff

Report bugs to <https://github.com/lepton-eda/lepton-eda/issues>
Lepton EDA homepage <https://github.com/lepton-eda/lepton-eda>
EOF

}

for PROG in lepton-schematic composite display
do
  if which $PROG > /dev/null
  then
    true
  else
    echo "$PROG is not found.  Either it is not installed, or not in your PATH"
    exit 1
  fi
done

if test $# -lt 2
  then usage; exit 1
fi

#In case the script was invoked with extra option arguments, throw them away
shift `expr $# - 2`

if test -d $1 -o -d $2
  then echo "ERROR: lepton-schdiff cannot diff entire directories"
  exit 1
fi

LEFTFILE=$1
RIGHTFILE=$2

LEFTPNG=`mktemp /tmp/lepton-schdiff-old.XXXXXXXXXX`
RIGHTPNG=`mktemp /tmp/lepton-schdiff-new.XXXXXXXXXX`
DIFFPNG=`mktemp /tmp/lepton-schdiff-diff.XXXXXXXXXX`

lepton-schematic -p -o $LEFTPNG -q -c '(image-size 1344 1008) (image-color "disabled") (gschem-use-rc-values) (gschem-image "dummyfilename") (gschem-exit)' $LEFTFILE && \
lepton-schematic -p -o $RIGHTPNG -q -c '(image-size 1344 1008) (image-color "disabled") (gschem-use-rc-values) (gschem-image "dummyfilename") (gschem-exit)' $RIGHTFILE && \
composite -stereo 0 $LEFTPNG $RIGHTPNG $DIFFPNG && \
display $DIFFPNG
rm $LEFTPNG
rm $RIGHTPNG
rm $DIFFPNG
