.TH mk_verilog_syms 1 "June 19th, 2011" "gEDA Project" 1.7.1.20110619
.SH NAME
mk_verilog_syms \- Create gate symbols for the gEDA Verilog netlister

.SH SYNOPSIS
.B mk_verilog_syms

.SH DESCRIPTION
.B mk_verilog_syms
creates a set of n-input gate symbols for the gEDA Verilog
netlister. It creates the following symbols:
.IP \(bu
and[2-9]
.IP \(bu
nand[2-9]
.IP \(bu
nor[2-9]
.IP \(bu
or[2-9]
.IP \(bu
xor[2-9]
.IP \(bu
xnor[2-9]

.SH AUTHOR
Mike Jarabek
.SH SEE ALSO
.BR gschem (1),
.BR gnetlist (1)
.SH COPYRIGHT
.nf
Copyright \(co 1999-2011 gEDA Contributors.  License GPLv2+: GNU GPL
version 2 or later.  Please see the `COPYING' file included with this
program for full details.
.PP
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
