@node Communication, Development, lepton-update, Top
@chapter Communication
@cindex communication
@cindex communication channels

We are using the following resources for almost all
communication about Lepton EDA and gEDA:

@itemize
@item
@url{https://github.com/lepton-eda/lepton-eda, our site on Github}:
report and discuss issues, add your patches, join to the project

@item
@url{https://app.gitter.im/#/room/#Lepton-EDA_Lobby:gitter.im, gitter.im chat room}: get in
touch with Lepton EDA users and developers

@item
@url{http://wiki.geda-project.org/geda:mailinglists, geda-user mailing
list}: discuss anything about Lepton and gEDA

@end itemize

Do not hesitate to get in touch the current maintainers privately.  We
very appreciate any contribution and would be glad to help you if you
have any trouble with Lepton.

We are interested in having new developers join and stay with our
project.  Get involved!
