@node lepton-netlist, lepton-cli, lepton-schematic, Top
@chapter Netlister
@pindex lepton-netlist
@cindex netlist
@cindex netlister

lepton-netlist is a Lepton netlister tool with command line interface.
It can be used directly on command line or in Makefiles to automate
your work.  This tool consists of a front-end and back-ends parts.
The front-end is the program itself which creates some internal
representation of schematic structure and does some post-processing.
The back-ends use this information to output into various formats for
use in other programs.  The user can write and use her custom back-end
or use several already existing backends included in the Lepton EDA
suite.

Below you'll find the list of back-ends available in Lepton.

@itemize
@item
allegro
@item
bae
@item
bom
@item
bom2
@item
calay
@item
cascade
@item
drc
@item
drc2
@item
eagle
@item
ewnet
@item
futurenet2
@item
geda
@item
gossip
@item
gsch2pcb
@item
liquidpcb
@item
makedepend
@item
mathematica
@item
maxascii
@item
osmond
@item
pads
@item
partslist1
@item
partslist2
@item
partslist3
@item
PCB
@item
pcbpins
@item
protelII
@item
redac
@item
spice
@item
spice-noqsi
@item
spice-sdb
@item
switcap
@item
systemc
@item
tango
@item
tEDAx
@item
vams
@item
verilog
@item
vhdl
@item
vipec
@end itemize

@menu
* Allegro backend::
* BAE backend::
* BOM backend::
* BOM2 backend::
* Calay backend::
* Cascade backend::
* PADS backend::
* ProtelII backend::
* Switcap backend::
@end menu

@include lepton-netlist-allegro.texi
@include lepton-netlist-bae.texi
@include lepton-netlist-bom.texi
@include lepton-netlist-bom2.texi
@include lepton-netlist-calay.texi
@include lepton-netlist-cascade.texi
@include lepton-netlist-pads.texi
@include lepton-netlist-protelii.texi
@include lepton-netlist-switcap.texi
