\input texinfo
@c -*-texinfo-*-
@c %**start of header
@setfilename lepton-manual.info
@include version.texi
@documentencoding UTF-8
@settitle Lepton EDA Reference Manual @value{VERSION}
@c %**end of header

@copying
This manual documents Lepton EDA version @value{VERSION}.

Copyright @copyright{} 2020-2022 Lepton Contributors.

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.  A
copy of the license is included in the section entitled ``GNU Free
Documentation License.''
@end copying

@dircategory Engineering
@direntry
* Lepton EDA: (lepton-manual). Lepton EDA Reference Manual
@end direntry

@titlepage
@title Lepton EDA Reference Manual
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@setchapternewpage odd

@c Output contents.
@contents

@ifnottex
@node Top, Overview, (dir), (dir)
@top Lepton EDA Reference Manual
@end ifnottex

@c Some aliases.
@alias attr=var
@alias cfgkey=code
@alias cfgtype=samp
@alias cfgval=samp

@c Some useful macros
@macro schematic
@command{lepton-schematic}
@end macro
@macro netlist
@command{lepton-netlist}
@end macro
@macro cli
@command{lepton-cli}
@end macro
@macro symcheck
@command{lepton-symcheck}
@end macro
@macro attrib
@command{lepton-attrib}
@end macro
@macro schpcb
@command{lepton-sch2pcb}
@end macro

@menu
* Overview::                    Overview of program components.
* Installation::                Installation of the tool suite.
* Configuration::               Configuration system.
* Logging::                     Search for important information.
* Symbols::
* lepton-schematic::            Lepton EDA schematic capture program.
* lepton-netlist::              Lepton EDA netlister.
* lepton-cli::                  Lepton EDA command line interface.
* lepton-attrib::               Lepton EDA spreadsheet attribute editor.
* lepton-update::
* Communication::               Places for discussions and chatting.
* Development::                 Useful information for developers.
* gEDA file format::            File format currently in use.
* Master attribute list::
* net= attribute mini-HOWTO::
* Lepton EDA fonts::
* Topic Index::
* Program Index::

@detailmenu
 --- The Detailed Node Listing ---

Overview

* List of programs::            The list of programs in the suite.
* Compatibility with geda-gaf::
* Related tools::               Tools related to Lepton EDA

Related tools

* Covered::

Installation

* Supported operating systems::
* Dependencies::
* Troubleshooting dependencies::
* Installation from source::
* Installation from git::
* Out-of-source build::
* Configure options::
* Hardcode library names for Guile::

Configuration system

* Introduction::                Introductory information.
* Legacy configuration::        Legacy configuration files still in use.
* New configuration system::    Overview of the new configuration system.
* Configuration of Lepton tools::  Configuration settings for particular Lepton tools.
* Deprecated settings::         Configuration settings having replacements.
* Obsolete settings::           Configuration settings no longer used.
* Resources::                   Other useful resources.

Legacy configuration files still in use

* gafrc::
* gschemrc::

Configuration settings for tools in the Lepton EDA suite

* lepton-schematic configuration::
* lepton-netlist configuration::
* lepton-cli configuration::

@command{Configuration of lepton-schematic}

* schematic.gui group::
* schematic.tabs group::
* schematic.status-bar group::
* schematic.undo group::
* schematic.log-window group::
* schematic.macro-widget group::
* schematic group::
* schematic.library group::
* schematic.printing group::
* schematic.backup group::
* schematic.attrib group::

@command{Configuration of lepton-netlist}

* netlist group::
* netlist.hierarchy group::

@command{Configuration of lepton-cli}

* export group::

Resources

* Documentation::
* Web pages::
* Utilities::
* Other resources::

Symbols

* Symbol Creation::
* Editing symbols::
* Editing symversion attribute::
* No-connect symbols::
* Title block symbol::
* Missing symbols::

Schematic capture

* Introduction to lepton-schematic::
* Running lepton-schematic::
* lepton-schematic window::
* Dialog boxes and widgets::
* Creating and opening schematics::
* Editing schematics::
* Working with windows::
* Quitting the program::
* Saving schematic pages::
* Printing and exporting::
* Selecting objects::
* Searching for text::
* Check symbols::
* lepton-schematic command line options::
* Component libraries::
* Interactive work with Scheme code::

Main lepton-schematic window

* Menubar::
* Menu File::
* Menu Edit::
* Menu View::
* Menu Page::
* Menu Add::
* Menu Hierarchy::
* Menu Attributes::
* Menu Options::
* Menu Netlist::
* Menu Help::
* Non-menu actions::

Dialog boxes and widgets

* Add Component widget::
* Save As dialog box::
* Log window::
* Macro widget::

Selecting objects

* Simple object selection::
* Box selection::
* Selecting and deselecting all objects::

Component libraries

* Component library setup::

Component library setup

* component-library::
* component-library-search::
* component-library-command::
* component-library-funcs::
* reset-component-library::

Netlister

* Allegro backend::
* BAE backend::
* BOM backend::
* BOM2 backend::
* Calay backend::
* Cascade backend::
* PADS backend::
* ProtelII backend::
* Switcap backend::

lepton-cli - Lepton command-line utility

* lepton-cli export:: Export images from schematic and symbol files.
* lepton-cli config:: Configure all Lepton tools.
* lepton-cli shell:: Scheme REPL for interactively processing schematics.

Introduction to lepton-attrib

* Usage of lepton-attrib::
* lepton-attrib menus::
* Installation of lepton-attrib::
* Credits and history of lepton-attrib::

Development

* Debugging::                   Debugging the tools

Debugging the tools

* Debug Scheme code::
* Debuggers::
* Debug Glib and GTK::

gEDA/gaf File Format Document

* File format overview::
* Coordinate space::
* Filenames::
* Object types::
* Colors::
* Attributes::
* Embedded Components::
* Path data::
* gEDA File Format Document Revision History::

Object types

* version::
* line::
* picture::
* box::
* circle::
* arc::
* text and attributes::
* net::
* bus::
* pin::
* component::
* path::
* font::

Master attribute list

* What are Attributes?::        What are attributes in a nutshell?
* Symbol only Attributes::      Attributes meaningful only for symbols.
* Schematic only Attributes::   Attributes meaningful only for schematics.
* Symbol and Schematic Attributes::  Attributes used ubiquitously.
* Obsolete Attributes::         Attributes no longer processed by the tools.
* Attribute compatibility::     Notable changes in Lepton compared to geda-gaf

Symbol only Attributes

* device attribute::
* graphical attribute::
* description attribute::
* author attribute::
* comment attribute::
* pinseq attribute::
* pinnumber attribute::
* pintype attribute::
* pinlabel attribute::
* numslots attribute::
* slotdef attribute::
* footprint attribute::
* documentation attribute::

Schematic only Attributes

* netname attribute::
* source attribute::

Symbol and Schematic Attributes

* refdes attribute::
* slot attribute::
* net attribute::
* value attribute::
* symversion attribute::
* dist-license attribute::
* use-license attribute::

refdes attribute

* refdes naming restrictions::
* refdes naming conventions::

Obsolete Attributes

* uref attribute::
* name attribute::
* label attribute::
* pin# attribute::
* slot# attribute::
* type attribute::
* email attribute::

@end detailmenu
@end menu

@include overview.texi
@include installation.texi
@include configuration.texi
@include logging.texi
@include symbols.texi
@include lepton-schematic.texi
@include lepton-netlist.texi
@include lepton-cli.texi
@include lepton-attrib.texi
@include lepton-update.texi
@include communication.texi
@include development.texi
@include geda-file-format-spec.texi
@include attributes.texi
@include attribute-net.texi
@include lepton-eda-fonts.texi
@include cindex.texi
@include pindex.texi

@bye
