@node Title block symbol,  , Symbols, Symbols
@section Title block symbol
@cindex title block symbol
@cindex title block
@cindex title-block symbol
@cindex title-block

The drawing area of @schematic{} is large enough and the users should
have representation of logical extents of the schematics they are
working on.  Title block symbol just aims to graphically define the
bounds of a created schematic page.

Title boxes are usually locked in order to prevent the user from
selecting it accidentally and deleting along with other objects.
Moreover, an unlocked title block would be confusingly selected
instead of other objects within it every now and then.  A title block
symbol is inserted any time the user creates a new schematic.  Since
it is not needed in symbols, you may want to delete it just after new
page creation.  Select it either by using @emph{box selection}
(@pxref{Box selection}) or @clicksequence{Edit @click{} Select Locked}
(@kbd{E K}) (@pxref{Selecting locked objects}) and hit @kbd{Delete}
or @kbd{E D}.

For historical reasons, the default title block symbol is
@file{title-B.sym}.  In order to set up another symbol as default
title block, change the @ref{default-titleblock} configuration key.
Choose the symbol you think will be used most often, and fix your
@ref{user-configuration, , user configuration}.  You may want to do
so for some project if only it needs other title blocks.  Amend your
@ref{project-configuration, , project configuration} in such a case.

@quotation Note
If you misspelled title block symbol name in your configuration
setting, or if the libraries linked in your project miss the symbol
with the name, or there is no symbol with specified system default
name when you did not changed the name in your local project
configuration, new untitled pages will be created empty, without any
title block.  See the log if in doubt (@ref{Logging}).
@xref{Missing symbols} for how to check that symbol has not been
found.
@end quotation

There are several predefined title block symbols in @schematic.  Open
the Add Component dialog box (@pxref{Add Component widget}) and enter
@kbd{title} in the filter entry to find them.
