.TH convert_sym 1 "June 19th, 2011" "gEDA project" 1.7.1.20110619

.SH NAME
convert_sym \- convert a Viewlogic symbol/schematic to gEDA gschem format

.SH SYNOPSIS
.B convert_sym
.I viewlogic_file

.SH DESCRIPTION
.B convert_sym
converts a Viewlogic symbol/schematic to gEDA
.B gschem
format. It accepts one argument, the name of the file to convert;
converted output is sent to stdout.

.SH AUTHOR
Mike Jarabek

.SH SEE ALSO
.BR gschem (1)

.SH COPYRIGHT
.nf
Copyright \(co 1999-2011 gEDA Contributors.  License GPLv2+: GNU GPL
version 2 or later.  Please see the `COPYING' file included with this
program for full details.
.PP
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

.
