.TH smash_megafile 1 "June 19th, 2011" "gEDA project" 1.7.1.20110619

.SH NAME
smash_megafile \- break a Viewlogic megafile into a million little pieces

.SH SYNOPSIS
.B smash_megafile
.I megafile

.SH OPTIONS
.TP
megafile
is the name of a Viewlogic megafile without any extensions. The file
<megafile>.lib and <megafile>.tbl must exist in the same directory.

.SH AUTHOR
Mike Jarabek

.SH COPYRIGHT
.nf
Copyright \(co 1999-2011 gEDA Contributors.  License GPLv2+: GNU GPL
version 2 or later.  Please see the `COPYING' file included with this
program for full details.
.PP
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
