\input texinfo @c -*-texinfo-*-
@c %** start of header
@setfilename gschemdoc.info
@settitle 
@c %**end of header

@dircategory Gschem source documentation
@direntry
* gschemdoc: (gschemdoc).         Gschem source documentation.
@end direntry


@c PART 2 : Summary Description and Copyright
@ifinfo

Copyright @copyright{} xxxx XXXX.
@end ifinfo


@c PART 3 : Titlepage and Copyright
@titlepage
@sp 10
@comment The title is printed in a large font.
@center @titlefont{Gschem source documentation}

@c The following two commands start the copyight page.
@page
@vskip 0pt plus 1filll
Copyright @copyright{} xxxx XXXX.
@end titlepage


@c PART 4 : 'Top' Node and Master Menu
@node Top,, (dir), (dir)
@top

@menu
* File a_pan.c:: file a_pan.c.
* File a_zoom.c:: file a_zoom.c.
* File g_funcs.c:: file g_funcs.c.
* File g_hook.c:: file g_hook.c.
* File g_key.c:: file g_key.c.
* File g_rc.c:: file g_rc.c.
* File g_register.c:: file g_register.c.
* File globals.c:: file globals.c.
* File gschem.c:: file gschem.c.
* File i_basic.c:: file i_basic.c.
* File i_callbacks.c:: file i_callbacks.c.
* File i_vars.c:: file i_vars.c.
* File o_arc.c:: file o_arc.c.
* File o_attrib.c:: file o_attrib.c.
* File o_basic.c:: file o_basic.c.
* File o_box.c:: file o_box.c.
* File o_buffer.c:: file o_buffer.c.
* File o_bus.c:: file o_bus.c.
* File o_circle.c:: file o_circle.c.
* File o_complex.c:: file o_complex.c.
* File o_copy.c:: file o_copy.c.
* File o_cue.c:: file o_cue.c.
* File o_delete.c:: file o_delete.c.
* File o_find.c:: file o_find.c.
* File o_grips.c:: file o_grips.c.
* File o_line.c:: file o_line.c.
* File o_misc.c:: file o_misc.c.
* File o_move.c:: file o_move.c.
* File o_net.c:: file o_net.c.
* File o_pin.c:: file o_pin.c.
* File o_select.c:: file o_select.c.
* File o_slot.c:: file o_slot.c.
* File o_text.c:: file o_text.c.
* File o_undo.c:: file o_undo.c.
* File parsecmd.c:: file parsecmd.c.
* File x_basic.c:: file x_basic.c.
* File x_color.c:: file x_color.c.
* File x_dialog.c:: file x_dialog.c.
* File x_event.c:: file x_event.c.
* File x_fileselect.c:: file x_fileselect.c.
* File x_grid.c:: file x_grid.c.
* File x_image.c:: file x_image.c.
* File x_log.c:: file x_log.c.
* File x_menus.c:: file x_menus.c.
* File x_multimulti.c:: file x_multimulti.c.
* File x_pagesel.c:: file x_pagesel.c.
* File x_preview.c:: file x_preview.c.
* File x_print.c:: file x_print.c.
* File x_script.c:: file x_script.c.
* File x_stroke.c:: file x_stroke.c.
* File x_window.c:: file x_window.c.

* Fonction Index:: all function names.
@end menu



@c PART 5 :C-source files
@include a_pan.texi
@include a_zoom.texi
@include g_funcs.texi
@include g_hook.texi
@include g_key.texi
@include g_rc.texi
@include g_register.texi
@include globals.texi
@include gschem.texi
@include i_basic.texi
@include i_callbacks.texi
@include i_vars.texi
@include o_arc.texi
@include o_attrib.texi
@include o_basic.texi
@include o_box.texi
@include o_buffer.texi
@include o_bus.texi
@include o_circle.texi
@include o_complex.texi
@include o_copy.texi
@include o_cue.texi
@include o_delete.texi
@include o_find.texi
@include o_grips.texi
@include o_line.texi
@include o_misc.texi
@include o_move.texi
@include o_net.texi
@include o_pin.texi
@include o_select.texi
@include o_slot.texi
@include o_text.texi
@include o_undo.texi
@include parsecmd.texi
@include x_basic.texi
@include x_color.texi
@include x_dialog.texi
@include x_event.texi
@include x_fileselect.texi
@include x_grid.texi
@include x_image.texi
@include x_log.texi
@include x_menus.texi
@include x_multimulti.texi
@include x_pagesel.texi
@include x_preview.texi
@include x_print.texi
@include x_script.texi
@include x_stroke.texi
@include x_window.texi

@c PART 6 : The End of the Document
@node Fonction Index,,,Top
@unnumbered Fonction Index

@printindex fn

@contents
@bye

