.TH gschem 1 "January 5th, 2010" "gEDA Project" 1.6.1.20100214
.SH NAME
gschem - gEDA/gaf Schematic Capture
.SH SYNOPSIS
.B gschem
[\fIOPTION\fR ...] [\fI--\fR] [\fIFILE\fR ...]
.SH DESCRIPTION
.PP
.B gschem
is a schematic capture application, and is part of the
gEDA (GPL Electronic Design Automation) toolset.  It is used to draw
electronic schematics, which describe the logical structure of an
circuit.  Schematics are made up of symbols, which represent the
various components in the circuit, and are obtained either from a
standard library or created by the user.  The connections between
components represented by nets (wires).  Schematics may be printed to
a PostScript file for printing or further conversion to other output
formats.  Output to various image formats is also supported.

.B gschem
can also be used for editing symbols for use in
schematics.

.SH OPTIONS
.TP 8
\fB-q\fR, \fB--quiet\fR
Quiet mode. Turn off all warnings/notes/messages.
.TP 8
\fB-v\fR, \fB--verbose\fR
Verbose mode.  Output all diagnostic information.
.TP 8
\fB-r\fR, \fB--config-file\fR=\fIFILE\fR
Specify an additional configuration file.  Normally \fBgschem\fR
searches for the system configuration file, then
`$HOME/.gEDA/gschemrc', and finally for a `gschemrc' file in the
current working directory.  This option allows the user to specify an
additional rc file which is read after all the other rc files have
been are read.
.TP 8
\fB-L\fR \fIDIRECTORY\fR
Prepend \fIDIRECTORY\fR to the list of directories to be searched for
Scheme files.
.TP 8
\fB-s\fR \fIFILE\fR
Specify a Scheme script to be executed at startup.
.TP 8
\fB-c\fR \fIEXPR\fR
Specify a Scheme expression to be evaluated at startup.
.TP 8
\fB-o\fR, \fB--output\fR=\fIFILE\fR
Specify a filename for PostScript output.  This command line argument
is useful when running \fBgschem\fR from a shell script and with a
Scheme script.  The filename can be changed through the print dialog
box.
.TP 8
\fB-p\fR
Automatically place the window. This may be useful if running \fBgschem\fR
from the command line and generating output.
.TP 8
\fB-h\fR, \fB--help\fR
Print a help message.
.TP 8
\fB-V\fR, \fB--version\fR
Print \fBgschem\fR version information.
.TP 8
\fB--\fR
Treat all remaining arguments as schematic or symbol filenames.  Use
this if you have a schematic or symbol filename which begins with `-'.

.SH SCHEMATIC AND SYMBOL FILES
Optionally, schematic or symbol \fIFILE\fRs may be specified on the
command line.  Any schematic or symbols specified are loaded at
startup as separate documents in the schematic editor.
.PP
If no \fIFILE\fRs are specified, a blank schematic is created for
editing.

.SH ENVIRONMENT
.TP 8
.B GEDADATA
specifies the search directory for Scheme and rc files.  The default
is `${prefix}/share/gEDA'.
.TP 8
.B GEDADATARC
specifies the search directory for rc files.  The default is `$GEDADATA'.

.SH AUTHORS
See the `AUTHORS' file included with this program.

.SH COPYRIGHT
.nf
Copyright \(co 1999-2011 gEDA Contributors.  License GPLv2+: GNU GPL
version 2 or later.  Please see the `COPYING' file included with this
program for full details.
.PP
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

.SH SEE ALSO
\fBgnetlist\fR(1), \fBgsymcheck\fR(1)
.PP
The full documentation for
.B gschem
is available from within the program by selecting the `gEDA
Documentation' option from the program's `Help' menu.
