#!/bin/sh

CFLAGS="`guile-config compile` `gtk-config --cflags`"

MISC_FLAGS="-I/usr/X11R6/include -I../include -I. -I.."

ALES_HACK=-D__GNUC__

cproto $ALES_HACK $CFLAGS $MISC_FLAGS *.c > new_proto

mv -f new_proto ../include/prototype.h
