/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_MainWindow (void)
{
  GtkWidget *MainWindow;
  GtkWidget *pMainVBox;
  GtkWidget *pMainNameHBox;
  GtkWidget *pMainNameLabel;
  GtkWidget *pMainNameEntry;
  GtkWidget *pMainNotebook;
  GtkWidget *pMainNotebookVBox;
  GtkWidget *pMainNotebookGraphFrame;
  GtkWidget *pMainNotebookGraphTable;
  GtkWidget *pMainNotebookGraphSourceCombo;
  GList *pMainNotebookGraphSourceCombo_items = NULL;
  GtkWidget *pMainNotebookGraphSourceEntry;
  GtkWidget *pMainNotebookGraphSourceLabel;
  GtkWidget *pMainNotebookGraphTypeLabel;
  GtkWidget *pMainNotebookGraphTypeCombo;
  GList *pMainNotebookGraphTypeCombo_items = NULL;
  GtkWidget *pMainNotebookGraphTypeEntry;
  GtkWidget *pMainNotebookGraphViewerLabel;
  GtkWidget *pMainNotebookGraphViewerCombo;
  GList *pMainNotebookGraphViewerCombo_items = NULL;
  GtkWidget *pMainNotebookGraphViewerEntry;
  GtkWidget *pMainNotebookGraphLabel;
  GtkWidget *pMainNotebookPlotsFrame;
  GtkWidget *pMainNotebookPlotsHBox;
  GtkWidget *pMainNotebookPlotsLeftVBox;
  GtkWidget *pMainNotebookPlotsListLabel;
  GtkWidget *pMainNotebookPlotsList;
  GtkWidget *pMainNotebookPlotsRightVBox;
  GtkWidget *pMainNotebookPlotsNewButton;
  GtkWidget *pMainNotebookPlotsModifyButton;
  GtkWidget *pMainNotebookPlotsDeleteButton;
  GtkWidget *pMainNotebookGraphVseparator;
  GtkWidget *pMainNotebookGraphBorderButton;
  GtkWidget *pMainNotebookPlotsLabel;
  GtkWidget *pMainNotebookXAxisVBox;
  GtkWidget *pMainNotebookXAxisScaleHBox;
  GtkWidget *pMainNotebookXAxisScaleFrame;
  GtkWidget *pMainNotebookXAxisScaleTable;
  GtkWidget *pMainNotebookXAxisScaleXminLabel;
  GtkWidget *pMainNotebookXAxisScaleXmaxLabel;
  GtkWidget *pMainNotebookXAxisScaleXminCheck;
  GtkWidget *pMainNotebookXAxisScaleLabel;
  GtkWidget *pMainNotebookXAxisScaleXmaxEntry;
  GtkWidget *pMainNotebookXaxisScaleCombo;
  GList *pMainNotebookXaxisScaleCombo_items = NULL;
  GtkWidget *pMainNotebookXaxisScaleEntry;
  GtkWidget *pMainNotebookXAxisScaleXminEntry;
  GtkWidget *pMainNotebookXAxisMainFrame;
  GtkWidget *pMainNotebookXAxisMainTable;
  GtkWidget *pMainNotebookXAxisMainDxLabel;
  GtkWidget *pMainNotebookXAxisMainDxCheck;
  GtkWidget *pMainNotebookXAxisMainStyleLabel;
  GtkWidget *pMainNotebookXAxisMainColorLabel;
  GtkWidget *pMainNotebookXAxisMainColorCombo;
  GList *pMainNotebookXAxisMainColorCombo_items = NULL;
  GtkWidget *pMainNotebookXAxisMainColorEntry;
  GtkWidget *pMainNotebookXAxisMainStyleCombo;
  GList *pMainNotebookXAxisMainStyleCombo_items = NULL;
  GtkWidget *pMainNotebookXAxisMainStyleEntry;
  GtkWidget *pMainNotebookXAxisMainDxEntry;
  GtkWidget *pMainNotebookXAxisAddFrame;
  GtkWidget *pMainNotebookXAxisAddTable;
  GtkWidget *pMainNotebookXAxisAddNumberLabel;
  GtkWidget *pMainNotebookXAxisAddNumberCheck;
  GtkWidget *pMainNotebookXAxisAddStyleLabel;
  GtkWidget *pMainNotebookXAxisAddColorLabel;
  GtkWidget *pMainNotebookXAxisAddStyleCombo;
  GList *pMainNotebookXAxisAddStyleCombo_items = NULL;
  GtkWidget *pMainNotebookXAxisAddStyleEntry;
  GtkWidget *pMainNotebookXAxisAddColorCombo;
  GList *pMainNotebookXAxisAddColorCombo_items = NULL;
  GtkWidget *pMainNotebookXAxisAddColorEntry;
  GtkWidget *pMainNotebookXAxisAddNumberEntry;
  GtkWidget *pMainNotebookXAxisLabel;
  GtkWidget *pMainNotebookYAxisVBox;
  GtkWidget *pMainNotebookYAxisScaleFrame;
  GtkWidget *pMainNotebookYAxisScaleTable;
  GtkWidget *pMainNotebookYAxisScaleYminLabel;
  GtkWidget *pMainNotebookYAxisScaleYmaxLabel;
  GtkWidget *pMainNotebookYAxisScaleYminCheck;
  GtkWidget *pMainNotebookYAxisScaleLabel;
  GtkWidget *pMainNotebookYAxisScaleYmaxEntry;
  GtkWidget *pMainNotebookYAxisScaleCombo;
  GList *pMainNotebookYAxisScaleCombo_items = NULL;
  GtkWidget *pMainNotebookYAxisScaleEntry;
  GtkWidget *pMainNotebookYAxisScaleYminEntry;
  GtkWidget *pMainNotebookYAxisMainFrame;
  GtkWidget *pMainNotebookYAxisMainTable;
  GtkWidget *pMainNotebookYAxisMainDyLabel;
  GtkWidget *pMainNotebookYAxisMainDyButton;
  GtkWidget *pMainNotebookYAxisMainStyleLabel;
  GtkWidget *pMainNotebookYAxisMainColorLabel;
  GtkWidget *pMainNotebookYAxisMainColorCombo;
  GList *pMainNotebookYAxisMainColorCombo_items = NULL;
  GtkWidget *pMainNotebookYAxisMainColorEntry;
  GtkWidget *pMainNotebookYAxisMainStyleCombo;
  GList *pMainNotebookYAxisMainStyleCombo_items = NULL;
  GtkWidget *pMainNotebookYAxisMainStyleEntry;
  GtkWidget *pMainNotebookYAxisMainDyEntry;
  GtkWidget *pMainNotebookYAxisAddFrame;
  GtkWidget *pMainNotebookYAxisAddTable;
  GtkWidget *pMainNotebookYAxisAddNumberLabel;
  GtkWidget *pMainNotebookYAxisAddNumberCheck;
  GtkWidget *pMainNotebookYAxisAddStyleLabel;
  GtkWidget *pMainNotebookYAxisAddColorLabel;
  GtkWidget *pMainNotebookYAxisAddStyleCombo;
  GList *pMainNotebookYAxisAddStyleCombo_items = NULL;
  GtkWidget *pMainNotebookYAxisAddStyleEntry;
  GtkWidget *pMainNotebookYAxisAddColorCombo;
  GList *pMainNotebookYAxisAddColorCombo_items = NULL;
  GtkWidget *pMainNotebookYAxisAddColorEntry;
  GtkWidget *pMainNotebookYAxisAddNumberEntry;
  GtkWidget *pMainNotebookYAxisLabel;
  GtkWidget *pMainButtonHBox;
  GtkWidget *pMainButtonOk;
  GtkWidget *pMainButtonCancel;
  GtkWidget *pMainButtonPlot;

  MainWindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (MainWindow), "MainWindow", MainWindow);
  gtk_window_set_title (GTK_WINDOW (MainWindow), _("Graph manager"));
  gtk_window_set_modal (GTK_WINDOW (MainWindow), TRUE);
  gtk_window_set_default_size (GTK_WINDOW (MainWindow), 510, 300);
  gtk_window_set_policy (GTK_WINDOW (MainWindow), FALSE, FALSE, TRUE);

  pMainVBox = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (pMainVBox);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainVBox", pMainVBox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainVBox);
  gtk_container_add (GTK_CONTAINER (MainWindow), pMainVBox);

  pMainNameHBox = gtk_hbox_new (FALSE, 8);
  gtk_widget_ref (pMainNameHBox);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNameHBox", pMainNameHBox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNameHBox);
  gtk_box_pack_start (GTK_BOX (pMainVBox), pMainNameHBox, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (pMainNameHBox), 8);

  pMainNameLabel = gtk_label_new (_("Graph name:"));
  gtk_widget_ref (pMainNameLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNameLabel", pMainNameLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNameLabel);
  gtk_box_pack_start (GTK_BOX (pMainNameHBox), pMainNameLabel, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (pMainNameLabel), GTK_JUSTIFY_LEFT);

  pMainNameEntry = gtk_entry_new ();
  gtk_widget_ref (pMainNameEntry);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNameEntry", pMainNameEntry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNameEntry);
  gtk_box_pack_start (GTK_BOX (pMainNameHBox), pMainNameEntry, TRUE, TRUE, 0);

  pMainNotebook = gtk_notebook_new ();
  gtk_widget_ref (pMainNotebook);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebook", pMainNotebook,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebook);
  gtk_box_pack_start (GTK_BOX (pMainVBox), pMainNotebook, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (pMainNotebook), 8);

  pMainNotebookVBox = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (pMainNotebookVBox);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookVBox", pMainNotebookVBox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookVBox);
  gtk_container_add (GTK_CONTAINER (pMainNotebook), pMainNotebookVBox);

  pMainNotebookGraphFrame = gtk_frame_new (_("Graph view"));
  gtk_widget_ref (pMainNotebookGraphFrame);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookGraphFrame", pMainNotebookGraphFrame,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookGraphFrame);
  gtk_box_pack_start (GTK_BOX (pMainNotebookVBox), pMainNotebookGraphFrame, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (pMainNotebookGraphFrame), 8);

  pMainNotebookGraphTable = gtk_table_new (3, 2, FALSE);
  gtk_widget_ref (pMainNotebookGraphTable);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookGraphTable", pMainNotebookGraphTable,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookGraphTable);
  gtk_container_add (GTK_CONTAINER (pMainNotebookGraphFrame), pMainNotebookGraphTable);
  gtk_container_set_border_width (GTK_CONTAINER (pMainNotebookGraphTable), 8);
  gtk_table_set_row_spacings (GTK_TABLE (pMainNotebookGraphTable), 8);
  gtk_table_set_col_spacings (GTK_TABLE (pMainNotebookGraphTable), 8);

  pMainNotebookGraphSourceCombo = gtk_combo_new ();
  gtk_widget_ref (pMainNotebookGraphSourceCombo);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookGraphSourceCombo", pMainNotebookGraphSourceCombo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookGraphSourceCombo);
  gtk_table_attach (GTK_TABLE (pMainNotebookGraphTable), pMainNotebookGraphSourceCombo, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  pMainNotebookGraphSourceCombo_items = g_list_append (pMainNotebookGraphSourceCombo_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (pMainNotebookGraphSourceCombo), pMainNotebookGraphSourceCombo_items);
  g_list_free (pMainNotebookGraphSourceCombo_items);

  pMainNotebookGraphSourceEntry = GTK_COMBO (pMainNotebookGraphSourceCombo)->entry;
  gtk_widget_ref (pMainNotebookGraphSourceEntry);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookGraphSourceEntry", pMainNotebookGraphSourceEntry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookGraphSourceEntry);

  pMainNotebookGraphSourceLabel = gtk_label_new (_("Data source:"));
  gtk_widget_ref (pMainNotebookGraphSourceLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookGraphSourceLabel", pMainNotebookGraphSourceLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookGraphSourceLabel);
  gtk_table_attach (GTK_TABLE (pMainNotebookGraphTable), pMainNotebookGraphSourceLabel, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (pMainNotebookGraphSourceLabel), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (pMainNotebookGraphSourceLabel), 7.45058e-09, 0.5);

  pMainNotebookGraphTypeLabel = gtk_label_new (_("Graph type:"));
  gtk_widget_ref (pMainNotebookGraphTypeLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookGraphTypeLabel", pMainNotebookGraphTypeLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookGraphTypeLabel);
  gtk_table_attach (GTK_TABLE (pMainNotebookGraphTable), pMainNotebookGraphTypeLabel, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (pMainNotebookGraphTypeLabel), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (pMainNotebookGraphTypeLabel), 0, 0.5);

  pMainNotebookGraphTypeCombo = gtk_combo_new ();
  gtk_widget_ref (pMainNotebookGraphTypeCombo);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookGraphTypeCombo", pMainNotebookGraphTypeCombo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookGraphTypeCombo);
  gtk_table_attach (GTK_TABLE (pMainNotebookGraphTable), pMainNotebookGraphTypeCombo, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  pMainNotebookGraphTypeCombo_items = g_list_append (pMainNotebookGraphTypeCombo_items, (gpointer) _("Rectangular plot"));
  gtk_combo_set_popdown_strings (GTK_COMBO (pMainNotebookGraphTypeCombo), pMainNotebookGraphTypeCombo_items);
  g_list_free (pMainNotebookGraphTypeCombo_items);

  pMainNotebookGraphTypeEntry = GTK_COMBO (pMainNotebookGraphTypeCombo)->entry;
  gtk_widget_ref (pMainNotebookGraphTypeEntry);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookGraphTypeEntry", pMainNotebookGraphTypeEntry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookGraphTypeEntry);
  gtk_entry_set_text (GTK_ENTRY (pMainNotebookGraphTypeEntry), _("Rectangular plot"));

  pMainNotebookGraphViewerLabel = gtk_label_new (_("Viewer:"));
  gtk_widget_ref (pMainNotebookGraphViewerLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookGraphViewerLabel", pMainNotebookGraphViewerLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookGraphViewerLabel);
  gtk_table_attach (GTK_TABLE (pMainNotebookGraphTable), pMainNotebookGraphViewerLabel, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (pMainNotebookGraphViewerLabel), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (pMainNotebookGraphViewerLabel), 0, 0.5);

  pMainNotebookGraphViewerCombo = gtk_combo_new ();
  gtk_widget_ref (pMainNotebookGraphViewerCombo);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookGraphViewerCombo", pMainNotebookGraphViewerCombo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookGraphViewerCombo);
  gtk_table_attach (GTK_TABLE (pMainNotebookGraphTable), pMainNotebookGraphViewerCombo, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  pMainNotebookGraphViewerCombo_items = g_list_append (pMainNotebookGraphViewerCombo_items, (gpointer) _("GNU GWave"));
  gtk_combo_set_popdown_strings (GTK_COMBO (pMainNotebookGraphViewerCombo), pMainNotebookGraphViewerCombo_items);
  g_list_free (pMainNotebookGraphViewerCombo_items);

  pMainNotebookGraphViewerEntry = GTK_COMBO (pMainNotebookGraphViewerCombo)->entry;
  gtk_widget_ref (pMainNotebookGraphViewerEntry);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookGraphViewerEntry", pMainNotebookGraphViewerEntry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookGraphViewerEntry);
  gtk_entry_set_text (GTK_ENTRY (pMainNotebookGraphViewerEntry), _("GNU GWave"));

  pMainNotebookGraphLabel = gtk_label_new (_("Graph"));
  gtk_widget_ref (pMainNotebookGraphLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookGraphLabel", pMainNotebookGraphLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookGraphLabel);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (pMainNotebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (pMainNotebook), 0), pMainNotebookGraphLabel);
  gtk_misc_set_padding (GTK_MISC (pMainNotebookGraphLabel), 4, 0);

  pMainNotebookPlotsFrame = gtk_frame_new (NULL);
  gtk_widget_ref (pMainNotebookPlotsFrame);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookPlotsFrame", pMainNotebookPlotsFrame,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookPlotsFrame);
  gtk_container_add (GTK_CONTAINER (pMainNotebook), pMainNotebookPlotsFrame);
  gtk_container_set_border_width (GTK_CONTAINER (pMainNotebookPlotsFrame), 8);

  pMainNotebookPlotsHBox = gtk_hbox_new (FALSE, 8);
  gtk_widget_ref (pMainNotebookPlotsHBox);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookPlotsHBox", pMainNotebookPlotsHBox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookPlotsHBox);
  gtk_container_add (GTK_CONTAINER (pMainNotebookPlotsFrame), pMainNotebookPlotsHBox);
  gtk_container_set_border_width (GTK_CONTAINER (pMainNotebookPlotsHBox), 8);

  pMainNotebookPlotsLeftVBox = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (pMainNotebookPlotsLeftVBox);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookPlotsLeftVBox", pMainNotebookPlotsLeftVBox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookPlotsLeftVBox);
  gtk_box_pack_start (GTK_BOX (pMainNotebookPlotsHBox), pMainNotebookPlotsLeftVBox, TRUE, TRUE, 0);

  pMainNotebookPlotsListLabel = gtk_label_new (_("Plots:"));
  gtk_widget_ref (pMainNotebookPlotsListLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookPlotsListLabel", pMainNotebookPlotsListLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookPlotsListLabel);
  gtk_box_pack_start (GTK_BOX (pMainNotebookPlotsLeftVBox), pMainNotebookPlotsListLabel, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (pMainNotebookPlotsListLabel), GTK_JUSTIFY_LEFT);

  pMainNotebookPlotsList = gtk_list_new ();
  gtk_widget_ref (pMainNotebookPlotsList);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookPlotsList", pMainNotebookPlotsList,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookPlotsList);
  gtk_box_pack_start (GTK_BOX (pMainNotebookPlotsLeftVBox), pMainNotebookPlotsList, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (pMainNotebookPlotsList), 8);

  pMainNotebookPlotsRightVBox = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (pMainNotebookPlotsRightVBox);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookPlotsRightVBox", pMainNotebookPlotsRightVBox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookPlotsRightVBox);
  gtk_box_pack_start (GTK_BOX (pMainNotebookPlotsHBox), pMainNotebookPlotsRightVBox, FALSE, FALSE, 0);

  pMainNotebookPlotsNewButton = gtk_button_new_with_label (_("New"));
  gtk_widget_ref (pMainNotebookPlotsNewButton);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookPlotsNewButton", pMainNotebookPlotsNewButton,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookPlotsNewButton);
  gtk_box_pack_start (GTK_BOX (pMainNotebookPlotsRightVBox), pMainNotebookPlotsNewButton, FALSE, FALSE, 0);
  gtk_widget_set_usize (pMainNotebookPlotsNewButton, 112, 48);
  gtk_container_set_border_width (GTK_CONTAINER (pMainNotebookPlotsNewButton), 8);
  GTK_WIDGET_SET_FLAGS (pMainNotebookPlotsNewButton, GTK_CAN_DEFAULT);

  pMainNotebookPlotsModifyButton = gtk_button_new_with_label (_("Modify"));
  gtk_widget_ref (pMainNotebookPlotsModifyButton);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookPlotsModifyButton", pMainNotebookPlotsModifyButton,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookPlotsModifyButton);
  gtk_box_pack_start (GTK_BOX (pMainNotebookPlotsRightVBox), pMainNotebookPlotsModifyButton, FALSE, FALSE, 0);
  gtk_widget_set_usize (pMainNotebookPlotsModifyButton, 112, 48);
  gtk_container_set_border_width (GTK_CONTAINER (pMainNotebookPlotsModifyButton), 8);
  GTK_WIDGET_SET_FLAGS (pMainNotebookPlotsModifyButton, GTK_CAN_DEFAULT);

  pMainNotebookPlotsDeleteButton = gtk_button_new_with_label (_("Delete"));
  gtk_widget_ref (pMainNotebookPlotsDeleteButton);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookPlotsDeleteButton", pMainNotebookPlotsDeleteButton,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookPlotsDeleteButton);
  gtk_box_pack_start (GTK_BOX (pMainNotebookPlotsRightVBox), pMainNotebookPlotsDeleteButton, FALSE, FALSE, 0);
  gtk_widget_set_usize (pMainNotebookPlotsDeleteButton, 112, 48);
  gtk_container_set_border_width (GTK_CONTAINER (pMainNotebookPlotsDeleteButton), 8);
  GTK_WIDGET_SET_FLAGS (pMainNotebookPlotsDeleteButton, GTK_CAN_DEFAULT);

  pMainNotebookGraphVseparator = gtk_vseparator_new ();
  gtk_widget_ref (pMainNotebookGraphVseparator);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookGraphVseparator", pMainNotebookGraphVseparator,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_box_pack_start (GTK_BOX (pMainNotebookPlotsRightVBox), pMainNotebookGraphVseparator, TRUE, TRUE, 0);

  pMainNotebookGraphBorderButton = gtk_button_new_with_label (_("Border"));
  gtk_widget_ref (pMainNotebookGraphBorderButton);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookGraphBorderButton", pMainNotebookGraphBorderButton,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookGraphBorderButton);
  gtk_box_pack_start (GTK_BOX (pMainNotebookPlotsRightVBox), pMainNotebookGraphBorderButton, FALSE, FALSE, 0);
  gtk_widget_set_usize (pMainNotebookGraphBorderButton, 112, 48);
  gtk_container_set_border_width (GTK_CONTAINER (pMainNotebookGraphBorderButton), 8);
  GTK_WIDGET_SET_FLAGS (pMainNotebookGraphBorderButton, GTK_CAN_DEFAULT);

  pMainNotebookPlotsLabel = gtk_label_new (_("Plots"));
  gtk_widget_ref (pMainNotebookPlotsLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookPlotsLabel", pMainNotebookPlotsLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookPlotsLabel);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (pMainNotebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (pMainNotebook), 1), pMainNotebookPlotsLabel);
  gtk_misc_set_padding (GTK_MISC (pMainNotebookPlotsLabel), 4, 0);

  pMainNotebookXAxisVBox = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (pMainNotebookXAxisVBox);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisVBox", pMainNotebookXAxisVBox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisVBox);
  gtk_container_add (GTK_CONTAINER (pMainNotebook), pMainNotebookXAxisVBox);

  pMainNotebookXAxisScaleHBox = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (pMainNotebookXAxisScaleHBox);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisScaleHBox", pMainNotebookXAxisScaleHBox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisScaleHBox);
  gtk_box_pack_start (GTK_BOX (pMainNotebookXAxisVBox), pMainNotebookXAxisScaleHBox, TRUE, TRUE, 0);

  pMainNotebookXAxisScaleFrame = gtk_frame_new (_("Scale"));
  gtk_widget_ref (pMainNotebookXAxisScaleFrame);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisScaleFrame", pMainNotebookXAxisScaleFrame,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisScaleFrame);
  gtk_box_pack_start (GTK_BOX (pMainNotebookXAxisScaleHBox), pMainNotebookXAxisScaleFrame, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (pMainNotebookXAxisScaleFrame), 8);

  pMainNotebookXAxisScaleTable = gtk_table_new (2, 6, FALSE);
  gtk_widget_ref (pMainNotebookXAxisScaleTable);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisScaleTable", pMainNotebookXAxisScaleTable,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisScaleTable);
  gtk_container_add (GTK_CONTAINER (pMainNotebookXAxisScaleFrame), pMainNotebookXAxisScaleTable);
  gtk_container_set_border_width (GTK_CONTAINER (pMainNotebookXAxisScaleTable), 8);
  gtk_table_set_row_spacings (GTK_TABLE (pMainNotebookXAxisScaleTable), 8);
  gtk_table_set_col_spacings (GTK_TABLE (pMainNotebookXAxisScaleTable), 8);

  pMainNotebookXAxisScaleXminLabel = gtk_label_new (_("X min"));
  gtk_widget_ref (pMainNotebookXAxisScaleXminLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisScaleXminLabel", pMainNotebookXAxisScaleXminLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisScaleXminLabel);
  gtk_table_attach (GTK_TABLE (pMainNotebookXAxisScaleTable), pMainNotebookXAxisScaleXminLabel, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (pMainNotebookXAxisScaleXminLabel, 40, -2);
  gtk_label_set_justify (GTK_LABEL (pMainNotebookXAxisScaleXminLabel), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (pMainNotebookXAxisScaleXminLabel), 0, 0.5);

  pMainNotebookXAxisScaleXmaxLabel = gtk_label_new (_("X max"));
  gtk_widget_ref (pMainNotebookXAxisScaleXmaxLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisScaleXmaxLabel", pMainNotebookXAxisScaleXmaxLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisScaleXmaxLabel);
  gtk_table_attach (GTK_TABLE (pMainNotebookXAxisScaleTable), pMainNotebookXAxisScaleXmaxLabel, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (pMainNotebookXAxisScaleXmaxLabel, 40, -2);
  gtk_label_set_justify (GTK_LABEL (pMainNotebookXAxisScaleXmaxLabel), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (pMainNotebookXAxisScaleXmaxLabel), 0, 0.5);

  pMainNotebookXAxisScaleXminCheck = gtk_check_button_new_with_label (_("Auto"));
  gtk_widget_ref (pMainNotebookXAxisScaleXminCheck);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisScaleXminCheck", pMainNotebookXAxisScaleXminCheck,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisScaleXminCheck);
  gtk_table_attach (GTK_TABLE (pMainNotebookXAxisScaleTable), pMainNotebookXAxisScaleXminCheck, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (pMainNotebookXAxisScaleXminCheck), TRUE);

  pMainNotebookXAxisScaleLabel = gtk_label_new (_("Scale"));
  gtk_widget_ref (pMainNotebookXAxisScaleLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisScaleLabel", pMainNotebookXAxisScaleLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisScaleLabel);
  gtk_table_attach (GTK_TABLE (pMainNotebookXAxisScaleTable), pMainNotebookXAxisScaleLabel, 4, 5, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (pMainNotebookXAxisScaleLabel, 40, -2);
  gtk_label_set_justify (GTK_LABEL (pMainNotebookXAxisScaleLabel), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (pMainNotebookXAxisScaleLabel), 0, 0.5);

  pMainNotebookXAxisScaleXmaxEntry = gtk_entry_new ();
  gtk_widget_ref (pMainNotebookXAxisScaleXmaxEntry);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisScaleXmaxEntry", pMainNotebookXAxisScaleXmaxEntry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisScaleXmaxEntry);
  gtk_table_attach (GTK_TABLE (pMainNotebookXAxisScaleTable), pMainNotebookXAxisScaleXmaxEntry, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_text (GTK_ENTRY (pMainNotebookXAxisScaleXmaxEntry), _("1.0"));

  pMainNotebookXaxisScaleCombo = gtk_combo_new ();
  gtk_widget_ref (pMainNotebookXaxisScaleCombo);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXaxisScaleCombo", pMainNotebookXaxisScaleCombo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXaxisScaleCombo);
  gtk_table_attach (GTK_TABLE (pMainNotebookXAxisScaleTable), pMainNotebookXaxisScaleCombo, 5, 6, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  pMainNotebookXaxisScaleCombo_items = g_list_append (pMainNotebookXaxisScaleCombo_items, (gpointer) _("Linear"));
  pMainNotebookXaxisScaleCombo_items = g_list_append (pMainNotebookXaxisScaleCombo_items, (gpointer) _("Logarithmic"));
  gtk_combo_set_popdown_strings (GTK_COMBO (pMainNotebookXaxisScaleCombo), pMainNotebookXaxisScaleCombo_items);
  g_list_free (pMainNotebookXaxisScaleCombo_items);

  pMainNotebookXaxisScaleEntry = GTK_COMBO (pMainNotebookXaxisScaleCombo)->entry;
  gtk_widget_ref (pMainNotebookXaxisScaleEntry);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXaxisScaleEntry", pMainNotebookXaxisScaleEntry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXaxisScaleEntry);
  gtk_entry_set_editable (GTK_ENTRY (pMainNotebookXaxisScaleEntry), FALSE);
  gtk_entry_set_text (GTK_ENTRY (pMainNotebookXaxisScaleEntry), _("Linear"));

  pMainNotebookXAxisScaleXminEntry = gtk_entry_new ();
  gtk_widget_ref (pMainNotebookXAxisScaleXminEntry);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisScaleXminEntry", pMainNotebookXAxisScaleXminEntry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisScaleXminEntry);
  gtk_table_attach (GTK_TABLE (pMainNotebookXAxisScaleTable), pMainNotebookXAxisScaleXminEntry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_text (GTK_ENTRY (pMainNotebookXAxisScaleXminEntry), _("0.0"));

  pMainNotebookXAxisMainFrame = gtk_frame_new (_("Main lines"));
  gtk_widget_ref (pMainNotebookXAxisMainFrame);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisMainFrame", pMainNotebookXAxisMainFrame,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisMainFrame);
  gtk_box_pack_start (GTK_BOX (pMainNotebookXAxisVBox), pMainNotebookXAxisMainFrame, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (pMainNotebookXAxisMainFrame), 8);

  pMainNotebookXAxisMainTable = gtk_table_new (2, 6, FALSE);
  gtk_widget_ref (pMainNotebookXAxisMainTable);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisMainTable", pMainNotebookXAxisMainTable,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisMainTable);
  gtk_container_add (GTK_CONTAINER (pMainNotebookXAxisMainFrame), pMainNotebookXAxisMainTable);
  gtk_container_set_border_width (GTK_CONTAINER (pMainNotebookXAxisMainTable), 8);
  gtk_table_set_row_spacings (GTK_TABLE (pMainNotebookXAxisMainTable), 8);
  gtk_table_set_col_spacings (GTK_TABLE (pMainNotebookXAxisMainTable), 8);

  pMainNotebookXAxisMainDxLabel = gtk_label_new (_("Dx"));
  gtk_widget_ref (pMainNotebookXAxisMainDxLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisMainDxLabel", pMainNotebookXAxisMainDxLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisMainDxLabel);
  gtk_table_attach (GTK_TABLE (pMainNotebookXAxisMainTable), pMainNotebookXAxisMainDxLabel, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (pMainNotebookXAxisMainDxLabel, 40, -2);
  gtk_label_set_justify (GTK_LABEL (pMainNotebookXAxisMainDxLabel), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (pMainNotebookXAxisMainDxLabel), 0, 0.5);

  pMainNotebookXAxisMainDxCheck = gtk_check_button_new_with_label (_("Auto"));
  gtk_widget_ref (pMainNotebookXAxisMainDxCheck);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisMainDxCheck", pMainNotebookXAxisMainDxCheck,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisMainDxCheck);
  gtk_table_attach (GTK_TABLE (pMainNotebookXAxisMainTable), pMainNotebookXAxisMainDxCheck, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (pMainNotebookXAxisMainDxCheck), TRUE);

  pMainNotebookXAxisMainStyleLabel = gtk_label_new (_("Style"));
  gtk_widget_ref (pMainNotebookXAxisMainStyleLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisMainStyleLabel", pMainNotebookXAxisMainStyleLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisMainStyleLabel);
  gtk_table_attach (GTK_TABLE (pMainNotebookXAxisMainTable), pMainNotebookXAxisMainStyleLabel, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (pMainNotebookXAxisMainStyleLabel, 40, -2);
  gtk_label_set_justify (GTK_LABEL (pMainNotebookXAxisMainStyleLabel), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (pMainNotebookXAxisMainStyleLabel), 0, 0.5);

  pMainNotebookXAxisMainColorLabel = gtk_label_new (_("Color"));
  gtk_widget_ref (pMainNotebookXAxisMainColorLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisMainColorLabel", pMainNotebookXAxisMainColorLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisMainColorLabel);
  gtk_table_attach (GTK_TABLE (pMainNotebookXAxisMainTable), pMainNotebookXAxisMainColorLabel, 4, 5, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (pMainNotebookXAxisMainColorLabel, 40, -2);
  gtk_label_set_justify (GTK_LABEL (pMainNotebookXAxisMainColorLabel), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (pMainNotebookXAxisMainColorLabel), 0, 0.5);

  pMainNotebookXAxisMainColorCombo = gtk_combo_new ();
  gtk_widget_ref (pMainNotebookXAxisMainColorCombo);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisMainColorCombo", pMainNotebookXAxisMainColorCombo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisMainColorCombo);
  gtk_table_attach (GTK_TABLE (pMainNotebookXAxisMainTable), pMainNotebookXAxisMainColorCombo, 5, 6, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  pMainNotebookXAxisMainColorCombo_items = g_list_append (pMainNotebookXAxisMainColorCombo_items, (gpointer) _("White"));
  pMainNotebookXAxisMainColorCombo_items = g_list_append (pMainNotebookXAxisMainColorCombo_items, (gpointer) _("Black"));
  pMainNotebookXAxisMainColorCombo_items = g_list_append (pMainNotebookXAxisMainColorCombo_items, (gpointer) _("Yellow"));
  pMainNotebookXAxisMainColorCombo_items = g_list_append (pMainNotebookXAxisMainColorCombo_items, (gpointer) _("Red"));
  pMainNotebookXAxisMainColorCombo_items = g_list_append (pMainNotebookXAxisMainColorCombo_items, (gpointer) _("Blue"));
  pMainNotebookXAxisMainColorCombo_items = g_list_append (pMainNotebookXAxisMainColorCombo_items, (gpointer) _("Green"));
  pMainNotebookXAxisMainColorCombo_items = g_list_append (pMainNotebookXAxisMainColorCombo_items, (gpointer) _("Orange"));
  pMainNotebookXAxisMainColorCombo_items = g_list_append (pMainNotebookXAxisMainColorCombo_items, (gpointer) _("Pink"));
  gtk_combo_set_popdown_strings (GTK_COMBO (pMainNotebookXAxisMainColorCombo), pMainNotebookXAxisMainColorCombo_items);
  g_list_free (pMainNotebookXAxisMainColorCombo_items);

  pMainNotebookXAxisMainColorEntry = GTK_COMBO (pMainNotebookXAxisMainColorCombo)->entry;
  gtk_widget_ref (pMainNotebookXAxisMainColorEntry);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisMainColorEntry", pMainNotebookXAxisMainColorEntry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisMainColorEntry);
  gtk_entry_set_text (GTK_ENTRY (pMainNotebookXAxisMainColorEntry), _("Black"));

  pMainNotebookXAxisMainStyleCombo = gtk_combo_new ();
  gtk_widget_ref (pMainNotebookXAxisMainStyleCombo);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisMainStyleCombo", pMainNotebookXAxisMainStyleCombo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisMainStyleCombo);
  gtk_table_attach (GTK_TABLE (pMainNotebookXAxisMainTable), pMainNotebookXAxisMainStyleCombo, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  pMainNotebookXAxisMainStyleCombo_items = g_list_append (pMainNotebookXAxisMainStyleCombo_items, (gpointer) _("SOLID"));
  gtk_combo_set_popdown_strings (GTK_COMBO (pMainNotebookXAxisMainStyleCombo), pMainNotebookXAxisMainStyleCombo_items);
  g_list_free (pMainNotebookXAxisMainStyleCombo_items);

  pMainNotebookXAxisMainStyleEntry = GTK_COMBO (pMainNotebookXAxisMainStyleCombo)->entry;
  gtk_widget_ref (pMainNotebookXAxisMainStyleEntry);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisMainStyleEntry", pMainNotebookXAxisMainStyleEntry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisMainStyleEntry);
  gtk_entry_set_text (GTK_ENTRY (pMainNotebookXAxisMainStyleEntry), _("SOLID"));

  pMainNotebookXAxisMainDxEntry = gtk_entry_new ();
  gtk_widget_ref (pMainNotebookXAxisMainDxEntry);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisMainDxEntry", pMainNotebookXAxisMainDxEntry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisMainDxEntry);
  gtk_table_attach (GTK_TABLE (pMainNotebookXAxisMainTable), pMainNotebookXAxisMainDxEntry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_text (GTK_ENTRY (pMainNotebookXAxisMainDxEntry), _("0.1"));

  pMainNotebookXAxisAddFrame = gtk_frame_new (_("Additional lines"));
  gtk_widget_ref (pMainNotebookXAxisAddFrame);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisAddFrame", pMainNotebookXAxisAddFrame,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisAddFrame);
  gtk_box_pack_start (GTK_BOX (pMainNotebookXAxisVBox), pMainNotebookXAxisAddFrame, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (pMainNotebookXAxisAddFrame), 8);

  pMainNotebookXAxisAddTable = gtk_table_new (2, 6, FALSE);
  gtk_widget_ref (pMainNotebookXAxisAddTable);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisAddTable", pMainNotebookXAxisAddTable,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisAddTable);
  gtk_container_add (GTK_CONTAINER (pMainNotebookXAxisAddFrame), pMainNotebookXAxisAddTable);
  gtk_container_set_border_width (GTK_CONTAINER (pMainNotebookXAxisAddTable), 8);
  gtk_table_set_row_spacings (GTK_TABLE (pMainNotebookXAxisAddTable), 8);
  gtk_table_set_col_spacings (GTK_TABLE (pMainNotebookXAxisAddTable), 8);

  pMainNotebookXAxisAddNumberLabel = gtk_label_new (_("Num"));
  gtk_widget_ref (pMainNotebookXAxisAddNumberLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisAddNumberLabel", pMainNotebookXAxisAddNumberLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisAddNumberLabel);
  gtk_table_attach (GTK_TABLE (pMainNotebookXAxisAddTable), pMainNotebookXAxisAddNumberLabel, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (pMainNotebookXAxisAddNumberLabel, 40, -2);
  gtk_label_set_justify (GTK_LABEL (pMainNotebookXAxisAddNumberLabel), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (pMainNotebookXAxisAddNumberLabel), 0, 0.5);

  pMainNotebookXAxisAddNumberCheck = gtk_check_button_new_with_label (_("Auto"));
  gtk_widget_ref (pMainNotebookXAxisAddNumberCheck);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisAddNumberCheck", pMainNotebookXAxisAddNumberCheck,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisAddNumberCheck);
  gtk_table_attach (GTK_TABLE (pMainNotebookXAxisAddTable), pMainNotebookXAxisAddNumberCheck, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (pMainNotebookXAxisAddNumberCheck), TRUE);

  pMainNotebookXAxisAddStyleLabel = gtk_label_new (_("Style"));
  gtk_widget_ref (pMainNotebookXAxisAddStyleLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisAddStyleLabel", pMainNotebookXAxisAddStyleLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisAddStyleLabel);
  gtk_table_attach (GTK_TABLE (pMainNotebookXAxisAddTable), pMainNotebookXAxisAddStyleLabel, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (pMainNotebookXAxisAddStyleLabel, 40, -2);
  gtk_label_set_justify (GTK_LABEL (pMainNotebookXAxisAddStyleLabel), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (pMainNotebookXAxisAddStyleLabel), 0, 0.5);

  pMainNotebookXAxisAddColorLabel = gtk_label_new (_("Color"));
  gtk_widget_ref (pMainNotebookXAxisAddColorLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisAddColorLabel", pMainNotebookXAxisAddColorLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisAddColorLabel);
  gtk_table_attach (GTK_TABLE (pMainNotebookXAxisAddTable), pMainNotebookXAxisAddColorLabel, 4, 5, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (pMainNotebookXAxisAddColorLabel, 40, -2);
  gtk_label_set_justify (GTK_LABEL (pMainNotebookXAxisAddColorLabel), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (pMainNotebookXAxisAddColorLabel), 0, 0.5);

  pMainNotebookXAxisAddStyleCombo = gtk_combo_new ();
  gtk_widget_ref (pMainNotebookXAxisAddStyleCombo);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisAddStyleCombo", pMainNotebookXAxisAddStyleCombo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisAddStyleCombo);
  gtk_table_attach (GTK_TABLE (pMainNotebookXAxisAddTable), pMainNotebookXAxisAddStyleCombo, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  pMainNotebookXAxisAddStyleCombo_items = g_list_append (pMainNotebookXAxisAddStyleCombo_items, (gpointer) _("SOLID"));
  gtk_combo_set_popdown_strings (GTK_COMBO (pMainNotebookXAxisAddStyleCombo), pMainNotebookXAxisAddStyleCombo_items);
  g_list_free (pMainNotebookXAxisAddStyleCombo_items);

  pMainNotebookXAxisAddStyleEntry = GTK_COMBO (pMainNotebookXAxisAddStyleCombo)->entry;
  gtk_widget_ref (pMainNotebookXAxisAddStyleEntry);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisAddStyleEntry", pMainNotebookXAxisAddStyleEntry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisAddStyleEntry);
  gtk_entry_set_text (GTK_ENTRY (pMainNotebookXAxisAddStyleEntry), _("SOLID"));

  pMainNotebookXAxisAddColorCombo = gtk_combo_new ();
  gtk_widget_ref (pMainNotebookXAxisAddColorCombo);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisAddColorCombo", pMainNotebookXAxisAddColorCombo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisAddColorCombo);
  gtk_table_attach (GTK_TABLE (pMainNotebookXAxisAddTable), pMainNotebookXAxisAddColorCombo, 5, 6, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  pMainNotebookXAxisAddColorCombo_items = g_list_append (pMainNotebookXAxisAddColorCombo_items, (gpointer) _("White"));
  pMainNotebookXAxisAddColorCombo_items = g_list_append (pMainNotebookXAxisAddColorCombo_items, (gpointer) _("Black"));
  pMainNotebookXAxisAddColorCombo_items = g_list_append (pMainNotebookXAxisAddColorCombo_items, (gpointer) _("Yellow"));
  pMainNotebookXAxisAddColorCombo_items = g_list_append (pMainNotebookXAxisAddColorCombo_items, (gpointer) _("Red"));
  pMainNotebookXAxisAddColorCombo_items = g_list_append (pMainNotebookXAxisAddColorCombo_items, (gpointer) _("Blue"));
  pMainNotebookXAxisAddColorCombo_items = g_list_append (pMainNotebookXAxisAddColorCombo_items, (gpointer) _("Green"));
  pMainNotebookXAxisAddColorCombo_items = g_list_append (pMainNotebookXAxisAddColorCombo_items, (gpointer) _("Orange"));
  pMainNotebookXAxisAddColorCombo_items = g_list_append (pMainNotebookXAxisAddColorCombo_items, (gpointer) _("Pink"));
  gtk_combo_set_popdown_strings (GTK_COMBO (pMainNotebookXAxisAddColorCombo), pMainNotebookXAxisAddColorCombo_items);
  g_list_free (pMainNotebookXAxisAddColorCombo_items);

  pMainNotebookXAxisAddColorEntry = GTK_COMBO (pMainNotebookXAxisAddColorCombo)->entry;
  gtk_widget_ref (pMainNotebookXAxisAddColorEntry);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisAddColorEntry", pMainNotebookXAxisAddColorEntry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisAddColorEntry);
  gtk_entry_set_text (GTK_ENTRY (pMainNotebookXAxisAddColorEntry), _("Black"));

  pMainNotebookXAxisAddNumberEntry = gtk_entry_new ();
  gtk_widget_ref (pMainNotebookXAxisAddNumberEntry);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisAddNumberEntry", pMainNotebookXAxisAddNumberEntry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisAddNumberEntry);
  gtk_table_attach (GTK_TABLE (pMainNotebookXAxisAddTable), pMainNotebookXAxisAddNumberEntry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_text (GTK_ENTRY (pMainNotebookXAxisAddNumberEntry), _("2"));

  pMainNotebookXAxisLabel = gtk_label_new (_("X axis"));
  gtk_widget_ref (pMainNotebookXAxisLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookXAxisLabel", pMainNotebookXAxisLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookXAxisLabel);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (pMainNotebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (pMainNotebook), 2), pMainNotebookXAxisLabel);
  gtk_misc_set_padding (GTK_MISC (pMainNotebookXAxisLabel), 4, 0);

  pMainNotebookYAxisVBox = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (pMainNotebookYAxisVBox);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisVBox", pMainNotebookYAxisVBox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisVBox);
  gtk_container_add (GTK_CONTAINER (pMainNotebook), pMainNotebookYAxisVBox);

  pMainNotebookYAxisScaleFrame = gtk_frame_new (_("Scale"));
  gtk_widget_ref (pMainNotebookYAxisScaleFrame);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisScaleFrame", pMainNotebookYAxisScaleFrame,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisScaleFrame);
  gtk_box_pack_start (GTK_BOX (pMainNotebookYAxisVBox), pMainNotebookYAxisScaleFrame, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (pMainNotebookYAxisScaleFrame), 8);

  pMainNotebookYAxisScaleTable = gtk_table_new (2, 6, FALSE);
  gtk_widget_ref (pMainNotebookYAxisScaleTable);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisScaleTable", pMainNotebookYAxisScaleTable,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisScaleTable);
  gtk_container_add (GTK_CONTAINER (pMainNotebookYAxisScaleFrame), pMainNotebookYAxisScaleTable);
  gtk_container_set_border_width (GTK_CONTAINER (pMainNotebookYAxisScaleTable), 8);
  gtk_table_set_row_spacings (GTK_TABLE (pMainNotebookYAxisScaleTable), 8);
  gtk_table_set_col_spacings (GTK_TABLE (pMainNotebookYAxisScaleTable), 8);

  pMainNotebookYAxisScaleYminLabel = gtk_label_new (_("Y min"));
  gtk_widget_ref (pMainNotebookYAxisScaleYminLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisScaleYminLabel", pMainNotebookYAxisScaleYminLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisScaleYminLabel);
  gtk_table_attach (GTK_TABLE (pMainNotebookYAxisScaleTable), pMainNotebookYAxisScaleYminLabel, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (pMainNotebookYAxisScaleYminLabel, 40, -2);
  gtk_label_set_justify (GTK_LABEL (pMainNotebookYAxisScaleYminLabel), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (pMainNotebookYAxisScaleYminLabel), 0, 0.5);

  pMainNotebookYAxisScaleYmaxLabel = gtk_label_new (_("Y max"));
  gtk_widget_ref (pMainNotebookYAxisScaleYmaxLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisScaleYmaxLabel", pMainNotebookYAxisScaleYmaxLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisScaleYmaxLabel);
  gtk_table_attach (GTK_TABLE (pMainNotebookYAxisScaleTable), pMainNotebookYAxisScaleYmaxLabel, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (pMainNotebookYAxisScaleYmaxLabel, 40, -2);
  gtk_label_set_justify (GTK_LABEL (pMainNotebookYAxisScaleYmaxLabel), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (pMainNotebookYAxisScaleYmaxLabel), 0, 0.5);

  pMainNotebookYAxisScaleYminCheck = gtk_check_button_new_with_label (_("Auto"));
  gtk_widget_ref (pMainNotebookYAxisScaleYminCheck);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisScaleYminCheck", pMainNotebookYAxisScaleYminCheck,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisScaleYminCheck);
  gtk_table_attach (GTK_TABLE (pMainNotebookYAxisScaleTable), pMainNotebookYAxisScaleYminCheck, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (pMainNotebookYAxisScaleYminCheck), TRUE);

  pMainNotebookYAxisScaleLabel = gtk_label_new (_("Scale"));
  gtk_widget_ref (pMainNotebookYAxisScaleLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisScaleLabel", pMainNotebookYAxisScaleLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisScaleLabel);
  gtk_table_attach (GTK_TABLE (pMainNotebookYAxisScaleTable), pMainNotebookYAxisScaleLabel, 4, 5, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (pMainNotebookYAxisScaleLabel, 40, -2);
  gtk_label_set_justify (GTK_LABEL (pMainNotebookYAxisScaleLabel), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (pMainNotebookYAxisScaleLabel), 0, 0.5);

  pMainNotebookYAxisScaleYmaxEntry = gtk_entry_new ();
  gtk_widget_ref (pMainNotebookYAxisScaleYmaxEntry);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisScaleYmaxEntry", pMainNotebookYAxisScaleYmaxEntry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisScaleYmaxEntry);
  gtk_table_attach (GTK_TABLE (pMainNotebookYAxisScaleTable), pMainNotebookYAxisScaleYmaxEntry, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_text (GTK_ENTRY (pMainNotebookYAxisScaleYmaxEntry), _("1.0"));

  pMainNotebookYAxisScaleCombo = gtk_combo_new ();
  gtk_widget_ref (pMainNotebookYAxisScaleCombo);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisScaleCombo", pMainNotebookYAxisScaleCombo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisScaleCombo);
  gtk_table_attach (GTK_TABLE (pMainNotebookYAxisScaleTable), pMainNotebookYAxisScaleCombo, 5, 6, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  pMainNotebookYAxisScaleCombo_items = g_list_append (pMainNotebookYAxisScaleCombo_items, (gpointer) _("Linear"));
  pMainNotebookYAxisScaleCombo_items = g_list_append (pMainNotebookYAxisScaleCombo_items, (gpointer) _("Logarithmic"));
  gtk_combo_set_popdown_strings (GTK_COMBO (pMainNotebookYAxisScaleCombo), pMainNotebookYAxisScaleCombo_items);
  g_list_free (pMainNotebookYAxisScaleCombo_items);

  pMainNotebookYAxisScaleEntry = GTK_COMBO (pMainNotebookYAxisScaleCombo)->entry;
  gtk_widget_ref (pMainNotebookYAxisScaleEntry);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisScaleEntry", pMainNotebookYAxisScaleEntry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisScaleEntry);
  gtk_entry_set_editable (GTK_ENTRY (pMainNotebookYAxisScaleEntry), FALSE);
  gtk_entry_set_text (GTK_ENTRY (pMainNotebookYAxisScaleEntry), _("Linear"));

  pMainNotebookYAxisScaleYminEntry = gtk_entry_new ();
  gtk_widget_ref (pMainNotebookYAxisScaleYminEntry);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisScaleYminEntry", pMainNotebookYAxisScaleYminEntry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisScaleYminEntry);
  gtk_table_attach (GTK_TABLE (pMainNotebookYAxisScaleTable), pMainNotebookYAxisScaleYminEntry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_text (GTK_ENTRY (pMainNotebookYAxisScaleYminEntry), _("0.0"));

  pMainNotebookYAxisMainFrame = gtk_frame_new (_("Main lines"));
  gtk_widget_ref (pMainNotebookYAxisMainFrame);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisMainFrame", pMainNotebookYAxisMainFrame,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisMainFrame);
  gtk_box_pack_start (GTK_BOX (pMainNotebookYAxisVBox), pMainNotebookYAxisMainFrame, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (pMainNotebookYAxisMainFrame), 8);

  pMainNotebookYAxisMainTable = gtk_table_new (2, 6, FALSE);
  gtk_widget_ref (pMainNotebookYAxisMainTable);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisMainTable", pMainNotebookYAxisMainTable,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisMainTable);
  gtk_container_add (GTK_CONTAINER (pMainNotebookYAxisMainFrame), pMainNotebookYAxisMainTable);
  gtk_container_set_border_width (GTK_CONTAINER (pMainNotebookYAxisMainTable), 8);
  gtk_table_set_row_spacings (GTK_TABLE (pMainNotebookYAxisMainTable), 8);
  gtk_table_set_col_spacings (GTK_TABLE (pMainNotebookYAxisMainTable), 8);

  pMainNotebookYAxisMainDyLabel = gtk_label_new (_("Dy"));
  gtk_widget_ref (pMainNotebookYAxisMainDyLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisMainDyLabel", pMainNotebookYAxisMainDyLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisMainDyLabel);
  gtk_table_attach (GTK_TABLE (pMainNotebookYAxisMainTable), pMainNotebookYAxisMainDyLabel, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (pMainNotebookYAxisMainDyLabel, 40, -2);
  gtk_label_set_justify (GTK_LABEL (pMainNotebookYAxisMainDyLabel), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (pMainNotebookYAxisMainDyLabel), 0, 0.5);

  pMainNotebookYAxisMainDyButton = gtk_check_button_new_with_label (_("Auto"));
  gtk_widget_ref (pMainNotebookYAxisMainDyButton);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisMainDyButton", pMainNotebookYAxisMainDyButton,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisMainDyButton);
  gtk_table_attach (GTK_TABLE (pMainNotebookYAxisMainTable), pMainNotebookYAxisMainDyButton, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (pMainNotebookYAxisMainDyButton), TRUE);

  pMainNotebookYAxisMainStyleLabel = gtk_label_new (_("Style"));
  gtk_widget_ref (pMainNotebookYAxisMainStyleLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisMainStyleLabel", pMainNotebookYAxisMainStyleLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisMainStyleLabel);
  gtk_table_attach (GTK_TABLE (pMainNotebookYAxisMainTable), pMainNotebookYAxisMainStyleLabel, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (pMainNotebookYAxisMainStyleLabel, 40, -2);
  gtk_label_set_justify (GTK_LABEL (pMainNotebookYAxisMainStyleLabel), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (pMainNotebookYAxisMainStyleLabel), 0, 0.5);

  pMainNotebookYAxisMainColorLabel = gtk_label_new (_("Color"));
  gtk_widget_ref (pMainNotebookYAxisMainColorLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisMainColorLabel", pMainNotebookYAxisMainColorLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisMainColorLabel);
  gtk_table_attach (GTK_TABLE (pMainNotebookYAxisMainTable), pMainNotebookYAxisMainColorLabel, 4, 5, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (pMainNotebookYAxisMainColorLabel, 40, -2);
  gtk_label_set_justify (GTK_LABEL (pMainNotebookYAxisMainColorLabel), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (pMainNotebookYAxisMainColorLabel), 0, 0.5);

  pMainNotebookYAxisMainColorCombo = gtk_combo_new ();
  gtk_widget_ref (pMainNotebookYAxisMainColorCombo);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisMainColorCombo", pMainNotebookYAxisMainColorCombo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisMainColorCombo);
  gtk_table_attach (GTK_TABLE (pMainNotebookYAxisMainTable), pMainNotebookYAxisMainColorCombo, 5, 6, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  pMainNotebookYAxisMainColorCombo_items = g_list_append (pMainNotebookYAxisMainColorCombo_items, (gpointer) _("White"));
  pMainNotebookYAxisMainColorCombo_items = g_list_append (pMainNotebookYAxisMainColorCombo_items, (gpointer) _("Black"));
  pMainNotebookYAxisMainColorCombo_items = g_list_append (pMainNotebookYAxisMainColorCombo_items, (gpointer) _("Yellow"));
  pMainNotebookYAxisMainColorCombo_items = g_list_append (pMainNotebookYAxisMainColorCombo_items, (gpointer) _("Red"));
  pMainNotebookYAxisMainColorCombo_items = g_list_append (pMainNotebookYAxisMainColorCombo_items, (gpointer) _("Blue"));
  pMainNotebookYAxisMainColorCombo_items = g_list_append (pMainNotebookYAxisMainColorCombo_items, (gpointer) _("Green"));
  pMainNotebookYAxisMainColorCombo_items = g_list_append (pMainNotebookYAxisMainColorCombo_items, (gpointer) _("Orange"));
  pMainNotebookYAxisMainColorCombo_items = g_list_append (pMainNotebookYAxisMainColorCombo_items, (gpointer) _("Pink"));
  gtk_combo_set_popdown_strings (GTK_COMBO (pMainNotebookYAxisMainColorCombo), pMainNotebookYAxisMainColorCombo_items);
  g_list_free (pMainNotebookYAxisMainColorCombo_items);

  pMainNotebookYAxisMainColorEntry = GTK_COMBO (pMainNotebookYAxisMainColorCombo)->entry;
  gtk_widget_ref (pMainNotebookYAxisMainColorEntry);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisMainColorEntry", pMainNotebookYAxisMainColorEntry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisMainColorEntry);
  gtk_entry_set_text (GTK_ENTRY (pMainNotebookYAxisMainColorEntry), _("Black"));

  pMainNotebookYAxisMainStyleCombo = gtk_combo_new ();
  gtk_widget_ref (pMainNotebookYAxisMainStyleCombo);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisMainStyleCombo", pMainNotebookYAxisMainStyleCombo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisMainStyleCombo);
  gtk_table_attach (GTK_TABLE (pMainNotebookYAxisMainTable), pMainNotebookYAxisMainStyleCombo, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  pMainNotebookYAxisMainStyleCombo_items = g_list_append (pMainNotebookYAxisMainStyleCombo_items, (gpointer) _("SOLID"));
  gtk_combo_set_popdown_strings (GTK_COMBO (pMainNotebookYAxisMainStyleCombo), pMainNotebookYAxisMainStyleCombo_items);
  g_list_free (pMainNotebookYAxisMainStyleCombo_items);

  pMainNotebookYAxisMainStyleEntry = GTK_COMBO (pMainNotebookYAxisMainStyleCombo)->entry;
  gtk_widget_ref (pMainNotebookYAxisMainStyleEntry);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisMainStyleEntry", pMainNotebookYAxisMainStyleEntry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisMainStyleEntry);
  gtk_entry_set_text (GTK_ENTRY (pMainNotebookYAxisMainStyleEntry), _("SOLID"));

  pMainNotebookYAxisMainDyEntry = gtk_entry_new ();
  gtk_widget_ref (pMainNotebookYAxisMainDyEntry);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisMainDyEntry", pMainNotebookYAxisMainDyEntry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisMainDyEntry);
  gtk_table_attach (GTK_TABLE (pMainNotebookYAxisMainTable), pMainNotebookYAxisMainDyEntry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_text (GTK_ENTRY (pMainNotebookYAxisMainDyEntry), _("0.1"));

  pMainNotebookYAxisAddFrame = gtk_frame_new (_("Additional lines"));
  gtk_widget_ref (pMainNotebookYAxisAddFrame);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisAddFrame", pMainNotebookYAxisAddFrame,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisAddFrame);
  gtk_box_pack_start (GTK_BOX (pMainNotebookYAxisVBox), pMainNotebookYAxisAddFrame, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (pMainNotebookYAxisAddFrame), 8);

  pMainNotebookYAxisAddTable = gtk_table_new (2, 6, FALSE);
  gtk_widget_ref (pMainNotebookYAxisAddTable);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisAddTable", pMainNotebookYAxisAddTable,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisAddTable);
  gtk_container_add (GTK_CONTAINER (pMainNotebookYAxisAddFrame), pMainNotebookYAxisAddTable);
  gtk_container_set_border_width (GTK_CONTAINER (pMainNotebookYAxisAddTable), 8);
  gtk_table_set_row_spacings (GTK_TABLE (pMainNotebookYAxisAddTable), 8);
  gtk_table_set_col_spacings (GTK_TABLE (pMainNotebookYAxisAddTable), 8);

  pMainNotebookYAxisAddNumberLabel = gtk_label_new (_("Num"));
  gtk_widget_ref (pMainNotebookYAxisAddNumberLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisAddNumberLabel", pMainNotebookYAxisAddNumberLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisAddNumberLabel);
  gtk_table_attach (GTK_TABLE (pMainNotebookYAxisAddTable), pMainNotebookYAxisAddNumberLabel, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (pMainNotebookYAxisAddNumberLabel, 40, -2);
  gtk_label_set_justify (GTK_LABEL (pMainNotebookYAxisAddNumberLabel), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (pMainNotebookYAxisAddNumberLabel), 0, 0.5);

  pMainNotebookYAxisAddNumberCheck = gtk_check_button_new_with_label (_("Auto"));
  gtk_widget_ref (pMainNotebookYAxisAddNumberCheck);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisAddNumberCheck", pMainNotebookYAxisAddNumberCheck,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisAddNumberCheck);
  gtk_table_attach (GTK_TABLE (pMainNotebookYAxisAddTable), pMainNotebookYAxisAddNumberCheck, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (pMainNotebookYAxisAddNumberCheck), TRUE);

  pMainNotebookYAxisAddStyleLabel = gtk_label_new (_("Style"));
  gtk_widget_ref (pMainNotebookYAxisAddStyleLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisAddStyleLabel", pMainNotebookYAxisAddStyleLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisAddStyleLabel);
  gtk_table_attach (GTK_TABLE (pMainNotebookYAxisAddTable), pMainNotebookYAxisAddStyleLabel, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (pMainNotebookYAxisAddStyleLabel, 40, -2);
  gtk_label_set_justify (GTK_LABEL (pMainNotebookYAxisAddStyleLabel), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (pMainNotebookYAxisAddStyleLabel), 0, 0.5);

  pMainNotebookYAxisAddColorLabel = gtk_label_new (_("Color"));
  gtk_widget_ref (pMainNotebookYAxisAddColorLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisAddColorLabel", pMainNotebookYAxisAddColorLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisAddColorLabel);
  gtk_table_attach (GTK_TABLE (pMainNotebookYAxisAddTable), pMainNotebookYAxisAddColorLabel, 4, 5, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (pMainNotebookYAxisAddColorLabel, 40, -2);
  gtk_label_set_justify (GTK_LABEL (pMainNotebookYAxisAddColorLabel), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (pMainNotebookYAxisAddColorLabel), 0, 0.5);

  pMainNotebookYAxisAddStyleCombo = gtk_combo_new ();
  gtk_widget_ref (pMainNotebookYAxisAddStyleCombo);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisAddStyleCombo", pMainNotebookYAxisAddStyleCombo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisAddStyleCombo);
  gtk_table_attach (GTK_TABLE (pMainNotebookYAxisAddTable), pMainNotebookYAxisAddStyleCombo, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  pMainNotebookYAxisAddStyleCombo_items = g_list_append (pMainNotebookYAxisAddStyleCombo_items, (gpointer) _("SOLID"));
  gtk_combo_set_popdown_strings (GTK_COMBO (pMainNotebookYAxisAddStyleCombo), pMainNotebookYAxisAddStyleCombo_items);
  g_list_free (pMainNotebookYAxisAddStyleCombo_items);

  pMainNotebookYAxisAddStyleEntry = GTK_COMBO (pMainNotebookYAxisAddStyleCombo)->entry;
  gtk_widget_ref (pMainNotebookYAxisAddStyleEntry);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisAddStyleEntry", pMainNotebookYAxisAddStyleEntry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisAddStyleEntry);
  gtk_entry_set_text (GTK_ENTRY (pMainNotebookYAxisAddStyleEntry), _("SOLID"));

  pMainNotebookYAxisAddColorCombo = gtk_combo_new ();
  gtk_widget_ref (pMainNotebookYAxisAddColorCombo);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisAddColorCombo", pMainNotebookYAxisAddColorCombo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisAddColorCombo);
  gtk_table_attach (GTK_TABLE (pMainNotebookYAxisAddTable), pMainNotebookYAxisAddColorCombo, 5, 6, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  pMainNotebookYAxisAddColorCombo_items = g_list_append (pMainNotebookYAxisAddColorCombo_items, (gpointer) _("White"));
  pMainNotebookYAxisAddColorCombo_items = g_list_append (pMainNotebookYAxisAddColorCombo_items, (gpointer) _("Black"));
  pMainNotebookYAxisAddColorCombo_items = g_list_append (pMainNotebookYAxisAddColorCombo_items, (gpointer) _("Yellow"));
  pMainNotebookYAxisAddColorCombo_items = g_list_append (pMainNotebookYAxisAddColorCombo_items, (gpointer) _("Red"));
  pMainNotebookYAxisAddColorCombo_items = g_list_append (pMainNotebookYAxisAddColorCombo_items, (gpointer) _("Blue"));
  pMainNotebookYAxisAddColorCombo_items = g_list_append (pMainNotebookYAxisAddColorCombo_items, (gpointer) _("Green"));
  pMainNotebookYAxisAddColorCombo_items = g_list_append (pMainNotebookYAxisAddColorCombo_items, (gpointer) _("Orange"));
  pMainNotebookYAxisAddColorCombo_items = g_list_append (pMainNotebookYAxisAddColorCombo_items, (gpointer) _("Pink"));
  gtk_combo_set_popdown_strings (GTK_COMBO (pMainNotebookYAxisAddColorCombo), pMainNotebookYAxisAddColorCombo_items);
  g_list_free (pMainNotebookYAxisAddColorCombo_items);

  pMainNotebookYAxisAddColorEntry = GTK_COMBO (pMainNotebookYAxisAddColorCombo)->entry;
  gtk_widget_ref (pMainNotebookYAxisAddColorEntry);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisAddColorEntry", pMainNotebookYAxisAddColorEntry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisAddColorEntry);
  gtk_entry_set_text (GTK_ENTRY (pMainNotebookYAxisAddColorEntry), _("Black"));

  pMainNotebookYAxisAddNumberEntry = gtk_entry_new ();
  gtk_widget_ref (pMainNotebookYAxisAddNumberEntry);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisAddNumberEntry", pMainNotebookYAxisAddNumberEntry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisAddNumberEntry);
  gtk_table_attach (GTK_TABLE (pMainNotebookYAxisAddTable), pMainNotebookYAxisAddNumberEntry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_text (GTK_ENTRY (pMainNotebookYAxisAddNumberEntry), _("2"));

  pMainNotebookYAxisLabel = gtk_label_new (_("Y axis"));
  gtk_widget_ref (pMainNotebookYAxisLabel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainNotebookYAxisLabel", pMainNotebookYAxisLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainNotebookYAxisLabel);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (pMainNotebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (pMainNotebook), 3), pMainNotebookYAxisLabel);
  gtk_misc_set_padding (GTK_MISC (pMainNotebookYAxisLabel), 4, 0);

  pMainButtonHBox = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (pMainButtonHBox);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainButtonHBox", pMainButtonHBox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainButtonHBox);
  gtk_box_pack_start (GTK_BOX (pMainVBox), pMainButtonHBox, FALSE, TRUE, 0);
  gtk_widget_set_usize (pMainButtonHBox, -2, 48);

  pMainButtonOk = gtk_button_new_with_label (_("Ok"));
  gtk_widget_ref (pMainButtonOk);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainButtonOk", pMainButtonOk,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainButtonOk);
  gtk_box_pack_start (GTK_BOX (pMainButtonHBox), pMainButtonOk, FALSE, FALSE, 0);
  gtk_widget_set_usize (pMainButtonOk, 112, 48);
  gtk_container_set_border_width (GTK_CONTAINER (pMainButtonOk), 8);
  GTK_WIDGET_SET_FLAGS (pMainButtonOk, GTK_CAN_DEFAULT);

  pMainButtonCancel = gtk_button_new_with_label (_("Cancel"));
  gtk_widget_ref (pMainButtonCancel);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainButtonCancel", pMainButtonCancel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainButtonCancel);
  gtk_box_pack_start (GTK_BOX (pMainButtonHBox), pMainButtonCancel, FALSE, FALSE, 0);
  gtk_widget_set_usize (pMainButtonCancel, 112, 48);
  gtk_container_set_border_width (GTK_CONTAINER (pMainButtonCancel), 8);
  GTK_WIDGET_SET_FLAGS (pMainButtonCancel, GTK_CAN_DEFAULT);

  pMainButtonPlot = gtk_button_new_with_label (_("Plot"));
  gtk_widget_ref (pMainButtonPlot);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "pMainButtonPlot", pMainButtonPlot,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pMainButtonPlot);
  gtk_box_pack_start (GTK_BOX (pMainButtonHBox), pMainButtonPlot, FALSE, FALSE, 0);
  gtk_widget_set_usize (pMainButtonPlot, 112, 48);
  gtk_container_set_border_width (GTK_CONTAINER (pMainButtonPlot), 8);
  GTK_WIDGET_SET_FLAGS (pMainButtonPlot, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (MainWindow), "delete_event",
                      GTK_SIGNAL_FUNC (MainDeleteEvent_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainNotebookGraphSourceEntry), "changed",
                      GTK_SIGNAL_FUNC (on_pMainNotebookGraphSourceEntry_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainNotebookGraphTypeEntry), "changed",
                      GTK_SIGNAL_FUNC (on_pMainNotebookGraphTypeEntry_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainNotebookGraphViewerEntry), "changed",
                      GTK_SIGNAL_FUNC (on_pMainNotebookGraphViewerEntry_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainNotebookPlotsNewButton), "clicked",
                      GTK_SIGNAL_FUNC (MainNotebookPlotsNewButton_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainNotebookPlotsModifyButton), "clicked",
                      GTK_SIGNAL_FUNC (MainNotebookPlotsModifyButton_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainNotebookPlotsDeleteButton), "clicked",
                      GTK_SIGNAL_FUNC (MainNotebookPlotsDeleteButton_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainNotebookGraphBorderButton), "clicked",
                      GTK_SIGNAL_FUNC (MainNotebookGraphBorderButton_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainNotebookXAxisScaleXminCheck), "toggled",
                      GTK_SIGNAL_FUNC (on_pMainNotebookXAxisScaleXminCheck_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainNotebookXAxisScaleXmaxEntry), "changed",
                      GTK_SIGNAL_FUNC (on_pMainNotebookXAxisScaleXmaxEntry_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainNotebookXaxisScaleEntry), "changed",
                      GTK_SIGNAL_FUNC (on_pMainNotebookXaxisScaleEntry_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainNotebookXAxisScaleXminEntry), "changed",
                      GTK_SIGNAL_FUNC (on_pMainNotebookXAxisScaleXminEntry_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainNotebookXAxisMainDxCheck), "toggled",
                      GTK_SIGNAL_FUNC (on_pMainNotebookXAxisMainDxCheck_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainNotebookXAxisMainColorEntry), "changed",
                      GTK_SIGNAL_FUNC (on_pMainNotebookXAxisMainColorEntry_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainNotebookXAxisMainStyleEntry), "changed",
                      GTK_SIGNAL_FUNC (on_pMainNotebookXAxisMainStyleEntry_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainNotebookXAxisMainDxEntry), "changed",
                      GTK_SIGNAL_FUNC (on_pMainNotebookXAxisMainDxEntry_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainNotebookXAxisAddNumberCheck), "toggled",
                      GTK_SIGNAL_FUNC (on_pMainNotebookXAxisAddNumberCheck_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainNotebookXAxisAddStyleEntry), "changed",
                      GTK_SIGNAL_FUNC (on_pMainNotebookXAxisAddStyleEntry_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainNotebookXAxisAddColorEntry), "changed",
                      GTK_SIGNAL_FUNC (on_pMainNotebookXAxisAddColorEntry_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainNotebookXAxisAddNumberEntry), "changed",
                      GTK_SIGNAL_FUNC (on_pMainNotebookXAxisAddNumberEntry_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainNotebookYAxisScaleYminCheck), "toggled",
                      GTK_SIGNAL_FUNC (on_pMainNotebookYAxisScaleYminCheck_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainNotebookYAxisScaleYmaxEntry), "changed",
                      GTK_SIGNAL_FUNC (on_pMainNotebookYAxisScaleYmaxEntry_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainNotebookYAxisScaleEntry), "changed",
                      GTK_SIGNAL_FUNC (on_pMainNotebookYAxisScaleEntry_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainNotebookYAxisScaleYminEntry), "changed",
                      GTK_SIGNAL_FUNC (on_pMainNotebookYAxisScaleYminEntry_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainNotebookYAxisMainDyButton), "toggled",
                      GTK_SIGNAL_FUNC (on_pMainNotebookYAxisMainDyButton_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainNotebookYAxisMainColorEntry), "changed",
                      GTK_SIGNAL_FUNC (on_pMainNotebookYAxisMainColorEntry_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainNotebookYAxisMainStyleEntry), "changed",
                      GTK_SIGNAL_FUNC (on_pMainNotebookYAxisMainStyleEntry_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainNotebookYAxisMainDyEntry), "changed",
                      GTK_SIGNAL_FUNC (on_pMainNotebookYAxisMainDyEntry_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainNotebookYAxisAddNumberCheck), "toggled",
                      GTK_SIGNAL_FUNC (on_pMainNotebookYAxisAddNumberCheck_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainNotebookYAxisAddStyleEntry), "changed",
                      GTK_SIGNAL_FUNC (on_pMainNotebookYAxisAddStyleEntry_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainNotebookYAxisAddColorEntry), "changed",
                      GTK_SIGNAL_FUNC (on_pMainNotebookYAxisAddColorEntry_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainNotebookYAxisAddNumberEntry), "changed",
                      GTK_SIGNAL_FUNC (on_pMainNotebookYAxisAddNumberEntry_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainButtonOk), "clicked",
                      GTK_SIGNAL_FUNC (MainButtonOk_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainButtonCancel), "clicked",
                      GTK_SIGNAL_FUNC (MainButtonCancel_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pMainButtonPlot), "clicked",
                      GTK_SIGNAL_FUNC (MainButtonPlot_clicked),
                      NULL);

  return MainWindow;
}

GtkWidget*
create_PlotWindow (void)
{
  GtkWidget *PlotWindow;
  GtkWidget *pPlotVBox;
  GtkWidget *pPlotDataHBox;
  GtkWidget *pPlotDataLabel;
  GtkWidget *pPlotDataEntry;
  GtkWidget *pPlotViewFrame;
  GtkWidget *pPlotViewTable;
  GtkWidget *pPlotViewStyleCombo;
  GtkWidget *pPlotViewStyleEntry;
  GtkWidget *pPlotViewPointsCombo;
  GtkWidget *pPlotViewPointsEntry;
  GtkWidget *pPlotViewColorCombo;
  GtkWidget *pPlotViewColorEntry;
  GtkWidget *pPlotViewStyleLabel;
  GtkWidget *pPlotViewPointsLabel;
  GtkWidget *pPlotViewColorLabel;
  GtkWidget *pPlotButtonHBox;
  GtkWidget *pPlotButtonOkButton;
  GtkWidget *pPlotButtonCancelButton;

  PlotWindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (PlotWindow), "PlotWindow", PlotWindow);
  gtk_window_set_title (GTK_WINDOW (PlotWindow), _("Graph plot"));
  gtk_window_set_modal (GTK_WINDOW (PlotWindow), TRUE);
  gtk_window_set_policy (GTK_WINDOW (PlotWindow), FALSE, FALSE, TRUE);

  pPlotVBox = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (pPlotVBox);
  gtk_object_set_data_full (GTK_OBJECT (PlotWindow), "pPlotVBox", pPlotVBox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pPlotVBox);
  gtk_container_add (GTK_CONTAINER (PlotWindow), pPlotVBox);

  pPlotDataHBox = gtk_hbox_new (FALSE, 8);
  gtk_widget_ref (pPlotDataHBox);
  gtk_object_set_data_full (GTK_OBJECT (PlotWindow), "pPlotDataHBox", pPlotDataHBox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pPlotDataHBox);
  gtk_box_pack_start (GTK_BOX (pPlotVBox), pPlotDataHBox, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (pPlotDataHBox), 8);

  pPlotDataLabel = gtk_label_new (_("Data"));
  gtk_widget_ref (pPlotDataLabel);
  gtk_object_set_data_full (GTK_OBJECT (PlotWindow), "pPlotDataLabel", pPlotDataLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pPlotDataLabel);
  gtk_box_pack_start (GTK_BOX (pPlotDataHBox), pPlotDataLabel, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (pPlotDataLabel), GTK_JUSTIFY_LEFT);

  pPlotDataEntry = gtk_entry_new ();
  gtk_widget_ref (pPlotDataEntry);
  gtk_object_set_data_full (GTK_OBJECT (PlotWindow), "pPlotDataEntry", pPlotDataEntry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pPlotDataEntry);
  gtk_box_pack_start (GTK_BOX (pPlotDataHBox), pPlotDataEntry, TRUE, TRUE, 0);

  pPlotViewFrame = gtk_frame_new (_("Plot view"));
  gtk_widget_ref (pPlotViewFrame);
  gtk_object_set_data_full (GTK_OBJECT (PlotWindow), "pPlotViewFrame", pPlotViewFrame,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pPlotViewFrame);
  gtk_box_pack_start (GTK_BOX (pPlotVBox), pPlotViewFrame, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (pPlotViewFrame), 8);

  pPlotViewTable = gtk_table_new (3, 2, FALSE);
  gtk_widget_ref (pPlotViewTable);
  gtk_object_set_data_full (GTK_OBJECT (PlotWindow), "pPlotViewTable", pPlotViewTable,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pPlotViewTable);
  gtk_container_add (GTK_CONTAINER (pPlotViewFrame), pPlotViewTable);
  gtk_container_set_border_width (GTK_CONTAINER (pPlotViewTable), 8);
  gtk_table_set_row_spacings (GTK_TABLE (pPlotViewTable), 8);
  gtk_table_set_col_spacings (GTK_TABLE (pPlotViewTable), 8);

  pPlotViewStyleCombo = gtk_combo_new ();
  gtk_widget_ref (pPlotViewStyleCombo);
  gtk_object_set_data_full (GTK_OBJECT (PlotWindow), "pPlotViewStyleCombo", pPlotViewStyleCombo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pPlotViewStyleCombo);
  gtk_table_attach (GTK_TABLE (pPlotViewTable), pPlotViewStyleCombo, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  pPlotViewStyleEntry = GTK_COMBO (pPlotViewStyleCombo)->entry;
  gtk_widget_ref (pPlotViewStyleEntry);
  gtk_object_set_data_full (GTK_OBJECT (PlotWindow), "pPlotViewStyleEntry", pPlotViewStyleEntry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pPlotViewStyleEntry);

  pPlotViewPointsCombo = gtk_combo_new ();
  gtk_widget_ref (pPlotViewPointsCombo);
  gtk_object_set_data_full (GTK_OBJECT (PlotWindow), "pPlotViewPointsCombo", pPlotViewPointsCombo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pPlotViewPointsCombo);
  gtk_table_attach (GTK_TABLE (pPlotViewTable), pPlotViewPointsCombo, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  pPlotViewPointsEntry = GTK_COMBO (pPlotViewPointsCombo)->entry;
  gtk_widget_ref (pPlotViewPointsEntry);
  gtk_object_set_data_full (GTK_OBJECT (PlotWindow), "pPlotViewPointsEntry", pPlotViewPointsEntry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pPlotViewPointsEntry);

  pPlotViewColorCombo = gtk_combo_new ();
  gtk_widget_ref (pPlotViewColorCombo);
  gtk_object_set_data_full (GTK_OBJECT (PlotWindow), "pPlotViewColorCombo", pPlotViewColorCombo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pPlotViewColorCombo);
  gtk_table_attach (GTK_TABLE (pPlotViewTable), pPlotViewColorCombo, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  pPlotViewColorEntry = GTK_COMBO (pPlotViewColorCombo)->entry;
  gtk_widget_ref (pPlotViewColorEntry);
  gtk_object_set_data_full (GTK_OBJECT (PlotWindow), "pPlotViewColorEntry", pPlotViewColorEntry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pPlotViewColorEntry);

  pPlotViewStyleLabel = gtk_label_new (_("Style"));
  gtk_widget_ref (pPlotViewStyleLabel);
  gtk_object_set_data_full (GTK_OBJECT (PlotWindow), "pPlotViewStyleLabel", pPlotViewStyleLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pPlotViewStyleLabel);
  gtk_table_attach (GTK_TABLE (pPlotViewTable), pPlotViewStyleLabel, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pPlotViewStyleLabel), 0, 0.5);

  pPlotViewPointsLabel = gtk_label_new (_("Points"));
  gtk_widget_ref (pPlotViewPointsLabel);
  gtk_object_set_data_full (GTK_OBJECT (PlotWindow), "pPlotViewPointsLabel", pPlotViewPointsLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pPlotViewPointsLabel);
  gtk_table_attach (GTK_TABLE (pPlotViewTable), pPlotViewPointsLabel, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pPlotViewPointsLabel), 0, 0.5);

  pPlotViewColorLabel = gtk_label_new (_("Color"));
  gtk_widget_ref (pPlotViewColorLabel);
  gtk_object_set_data_full (GTK_OBJECT (PlotWindow), "pPlotViewColorLabel", pPlotViewColorLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pPlotViewColorLabel);
  gtk_table_attach (GTK_TABLE (pPlotViewTable), pPlotViewColorLabel, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pPlotViewColorLabel), 0, 0.5);

  pPlotButtonHBox = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (pPlotButtonHBox);
  gtk_object_set_data_full (GTK_OBJECT (PlotWindow), "pPlotButtonHBox", pPlotButtonHBox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pPlotButtonHBox);
  gtk_box_pack_start (GTK_BOX (pPlotVBox), pPlotButtonHBox, FALSE, TRUE, 0);
  gtk_widget_set_usize (pPlotButtonHBox, -2, 48);

  pPlotButtonOkButton = gtk_button_new_with_label (_("Ok"));
  gtk_widget_ref (pPlotButtonOkButton);
  gtk_object_set_data_full (GTK_OBJECT (PlotWindow), "pPlotButtonOkButton", pPlotButtonOkButton,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pPlotButtonOkButton);
  gtk_box_pack_start (GTK_BOX (pPlotButtonHBox), pPlotButtonOkButton, FALSE, FALSE, 0);
  gtk_widget_set_usize (pPlotButtonOkButton, 112, 48);
  gtk_container_set_border_width (GTK_CONTAINER (pPlotButtonOkButton), 8);
  GTK_WIDGET_SET_FLAGS (pPlotButtonOkButton, GTK_CAN_DEFAULT);

  pPlotButtonCancelButton = gtk_button_new_with_label (_("Cancel"));
  gtk_widget_ref (pPlotButtonCancelButton);
  gtk_object_set_data_full (GTK_OBJECT (PlotWindow), "pPlotButtonCancelButton", pPlotButtonCancelButton,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pPlotButtonCancelButton);
  gtk_box_pack_start (GTK_BOX (pPlotButtonHBox), pPlotButtonCancelButton, FALSE, FALSE, 0);
  gtk_widget_set_usize (pPlotButtonCancelButton, 112, 48);
  gtk_container_set_border_width (GTK_CONTAINER (pPlotButtonCancelButton), 8);
  GTK_WIDGET_SET_FLAGS (pPlotButtonCancelButton, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (pPlotButtonOkButton), "clicked",
                      GTK_SIGNAL_FUNC (PlotButtonOkButton_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (pPlotButtonCancelButton), "clicked",
                      GTK_SIGNAL_FUNC (PlotButtonCancelButton_clicked),
                      NULL);

  return PlotWindow;
}

