#!/bin/sh

# run tragesym over all test and example files

exe=../../scripts/lepton-tragesym

echo testing 4099.src
$exe 4099.src 4099.sym
echo

echo testing test1.src
$exe  test1.src test1.sym
echo

echo testing test2.src
$exe  test2.src test2.sym
echo

echo testing test3.src
$exe  test3.src test3.sym
echo

echo testing AT90S8535_TQFP.src
$exe  AT90S8535_TQFP.src AT90S8535_TQFP.sym
echo
