#ifndef __pixmap_h__
#define __pixmap_h__

/* XPM */
static char * bullet_xpm[] = {
"16 16 26 1",
" 	c #None",
".	c #000000000000",
"X	c #0000E38D0000",
"o	c #0000EBAD0000",
"O	c #0000F7DE0000",
"+	c #0000FFFF0000",
"@	c #0000CF3C0000",
"#	c #0000D75C0000",
"$	c #0000B6DA0000",
"%	c #0000C30B0000",
"&	c #0000A2890000",
"*	c #00009A690000",
"=	c #0000AEBA0000",
"-	c #00008E380000",
";	c #000086170000",
":	c #000079E70000",
">	c #000071C60000",
",	c #000065950000",
"<	c #000059650000",
"1	c #000051440000",
"2	c #000045140000",
"3	c #00003CF30000",
"4	c #000030C20000",
"5	c #000028A20000",
"6	c #00001C710000",
"7	c #000014510000",
"     ......     ",
"    .XooO++.    ",
"  ..@@@#XoO+..  ",
" .$$$$$%@#XO++. ",
" .&&*&&=$%@XO+. ",
".*-;;;-*&=%@XO+.",
".;:>>>:;-&=%#o+.",
".>,<<<,>:-&$@XO.",
".<12321<>;*=%#o.",
".1345431,:-&$@o.",
".2467642<>;&$@X.",
" .57.753<>;*$@. ",
" .467642<>;&$@. ",
"  ..5431,:-&..  ",
"    .21<>;*.    ",
"     ......     "};

/* XPM */
static char *center_just [] =
{
  "28 26 2 1",
  ".      c #None",
  "X      c #000000000000",
  "                            ",
  "                            ",
  "                            ",
  "                            ",
  "     XXXXXXXXXXXXXXXXXX     ",
  "     XXXXXXXXXXXXXXXXXX     ",
  "                            ",
  "        XXXXXXXXXXXX        ",
  "        XXXXXXXXXXXX        ",
  "                            ",
  "     XXXXXXXXXXXXXXXXXX     ",
  "     XXXXXXXXXXXXXXXXXX     ",
  "                            ",
  "        XXXXXXXXXXXX        ",
  "        XXXXXXXXXXXX        ",
  "                            ",
  "     XXXXXXXXXXXXXXXXXX     ",
  "     XXXXXXXXXXXXXXXXXX     ",
  "                            ",
  "        XXXXXXXXXXXX        ",
  "        XXXXXXXXXXXX        ",
  "                            ",
  "                            ",
  "                            ",
  "                            ",
  "                            ",
};
/* XPM */
static char * font[] = {
"26 26 3 1",
" 	c #None",
".	c #000000000000",
"X	c #000000000000",
"                          ",
"                          ",
"                          ",
"            .             ",
"           ...            ",
"           ...            ",
"          .....           ",
"          .....           ",
"         .. ....          ",
"         .. ....          ",
"        ..   ....         ",
"        .........         ",
"       ...........        ",
"       ..     ....        ",
"      ..       ....       ",
"      ..       ....       ",
"    .....     .......     ",
"                          ",
"                          ",
"                          ",
"     XXXXXXXXXXXXXXXX     ",
"     XXXXXXXXXXXXXXXX     ",
"     XXXXXXXXXXXXXXXX     ",
"     XXXXXXXXXXXXXXXX     ",
"                          ",
"                          ",
"                          "};
/* XPM */
static char *left_just [] =
{
  "28 26 2 1",
  ".      c #None",
  "X      c #000000000000",
  "                            ",
  "                            ",
  "                            ",
  "                            ",
  "     XXXXXXXXXXXXXXXXXX     ",
  "     XXXXXXXXXXXXXXXXXX     ",
  "                            ",
  "     XXXXXXXXXXXXX          ",
  "     XXXXXXXXXXXXX          ",
  "                            ",
  "     XXXXXXXXXXXXXXXXXX     ",
  "     XXXXXXXXXXXXXXXXXX     ",
  "                            ",
  "     XXXXXXXXXXXXX          ",
  "     XXXXXXXXXXXXX          ",
  "                            ",
  "     XXXXXXXXXXXXXXXXXX     ",
  "     XXXXXXXXXXXXXXXXXX     ",
  "                            ",
  "     XXXXXXXXXXXXX          ",
  "     XXXXXXXXXXXXX          ",
  "                            ",
  "                            ",
  "                            ",
  "                            ",
  "                            ",
};
/* XPM */
static char *paint [] =
{
  "26 26 6 1",
  ".      c #None",
  "a      c #000000000000",
  "e      c #929292929292",
  "g      c #DBDBDBDBDBDB",
  "h      c #FFFFFFFFFFFF",
  "X      c #FFFFFFFFFFFF",
  "..........................",
  "...........ee.............",
  "..........eeee............",
  ".........eeggee...........",
  ".........eegaee...........",
  ".........eeahee...........",
  ".........aahheeaa.........",
  ".........ahhgeegaaa.......",
  "........ahhghaeggaaa......",
  ".......ahhghagaggeaaa.....",
  "......ahhghggaggeeaaae....",
  ".....ahhghgggggeeaaaae....",
  ".....ahghgggggeeaeaaae....",
  "......ahgggggeeaeeaaae....",
  ".......ahgggeeaee.aaae....",
  "........aggeeaee..aaee....",
  ".........aeeaee...aee.....",
  "..........aaee.....e......",
  "...........ee.............",
  "..........................",
  "....XXXXXXXXXXXXXXXXXX....",
  "....XXXXXXXXXXXXXXXXXX....",
  "....XXXXXXXXXXXXXXXXXX....",
  "....XXXXXXXXXXXXXXXXXX....",
  "..........................",
  "..........................",
};
/* XPM */
static char *right_just [] =
{
  "28 26 2 1",
  ".      c #None",
  "X      c #000000000000",
  "                            ",
  "                            ",
  "                            ",
  "                            ",
  "     XXXXXXXXXXXXXXXXXX     ",
  "     XXXXXXXXXXXXXXXXXX     ",
  "                            ",
  "          XXXXXXXXXXXXX     ",
  "          XXXXXXXXXXXXX     ",
  "                            ",
  "     XXXXXXXXXXXXXXXXXX     ",
  "     XXXXXXXXXXXXXXXXXX     ",
  "                            ",
  "          XXXXXXXXXXXXX     ",
  "          XXXXXXXXXXXXX     ",
  "                            ",
  "     XXXXXXXXXXXXXXXXXX     ",
  "     XXXXXXXXXXXXXXXXXX     ",
  "                            ",
  "          XXXXXXXXXXXXX     ",
  "          XXXXXXXXXXXXX     ",
  "                            ",
  "                            ",
  "                            ",
  "                            ",
  "                            ",
};

/* XPM */
static char * smile_xpm[] = {
"16 16 3 1",
" 	c #None",
".	c #000000000000",
"X	c #FFFFFFFF0000",
"     ......     ",
"    .XXXXXX.    ",
"  ..XXXXXXXX..  ",
" .XXXXXXXXXXXX. ",
" .XXX..XX..XXX. ",
".XXXX..XX..XXXX.",
".XXXX..XX..XXXX.",
".XXXXXXXXXXXXXX.",
".XX..XXXXXX..XX.",
".XX..XXXXXX..XX.",
".XXX.XXXXXX.XXX.",
" .XXX.XXXX.XXX. ",
" .XXXX....XXXX. ",
"  ..XXXXXXXX..  ",
"    .XXXXXX.    ",
"     ......     "};

#endif
